---
title: "MCCHD Covid-19 initial data cleaning"
author: "Ethan Walker"
date: "Started 11 April 2022, Updated 11 April 2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE)
```

```{r, message=FALSE, warning=F}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(plotly)
library(knitr)
```


```{r}
# Load data and format columns

input_path <- c("C:/Users/ethan.walker/Box/Missoula_COVID19EpiProfile_Working/")


covid_data_initial <- 
   read_xlsx(paste0(input_path, "COVID Data_04.11.2022.xlsx"), sheet = 1,
             range = "A2:P40000", na = c(" ", ""),
                        col_names = c("investigation_status", "inv_start_date", "health_worker", 
                                      "cong_living", "age", "age_unit",
                                      "sex", "zipcode", "test_date", "um_student", "race", 
                                      "ethnicity", "ever_hosp", "patient_died",
                                      "breakthrough_case", "reinfection_case"),
                        col_types = c("text", "date", "text",
                                      "text", "text", "text",
                                      "text", "text", "date", "text", "text",
                                      "text", "text", "text",
                                      "text", "text"))

#summary(covid_data_initial)
```


```{r}
# Clean data
covid_clean <- covid_data_initial %>% 
   # Filter out empty rows/observations
   filter(!is.na(investigation_status)) %>% 
   # Format age and age groups with age group percentages
   mutate(age = as.numeric(age),
          age_group = cut(age, breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 130),
                          labels = c("0 to 9, 0.101", "10 to 19, 0.117", "20 to 29, 0.191", 
                                     "30 to 39, 0.143", "40 to 49, 0.115", "50 to 59, 0.112", 
                                     "60 to 69, 0.118", "70 to 79, 0.072", "80+, 0.032"), right = FALSE),
          age_group2 = cut(age, breaks = c(0, 18, 65, 130),
                          labels = c("<18", "18 to 64", "65+"), right = FALSE),
          age_group3 = cut(age, breaks = c(0, 5, 14, 18, 25, 30, 40, 50, 60, 70, 80, 130),
                          labels = c("0 to 4, 0.0503", "5 to 13, 0.095", "14 to 17, 0.0405", 
                                     "18 to 24, 0.137", "25 to 29, 0.086", 
                                     "30 to 39, 0.143", "40 to 49, 0.115", "50 to 59, 0.112", 
                                     "60 to 69, 0.118", "70 to 79, 0.072", "80+, 0.032"), right = FALSE)) %>% 
   # Separate age groups from percentages
   separate(age_group, c("age_group", "age_group_percent"), sep = ", ") %>% 
   separate(age_group3, c("age_group3", "age_group3_percent"), sep = ", ") %>% 
   mutate(age_group_percent = as.numeric(age_group_percent),
          age_group3_percent = as.numeric(age_group3_percent)) %>% 
   # Format character variables to factor and lower case
   mutate_if(is.factor, tolower) %>% 
   mutate_if(is.character, tolower) %>% 
   mutate_if(is.character, as.factor) %>% 
   # Consistently label NA values throughout dataset
   replace_with_na_all(condition = ~.x %in% c("n/a", "na", "unknown", "unkown")) %>% 
   # Excel had dates formatted as datetime, so separate into date and time
   separate(test_date, into = c("test_date", "time"), sep = " ") %>% 
   separate(inv_start_date, into = c("inv_start_date", "time2"), sep = " ") %>% 
   # Format specific variables
   mutate(county_pop = as.numeric(119600),
          case = 1,
          hospitalizations = fct_collapse(ever_hosp,
                                          "no" = c("n", NA),
                                          "yes" = c("y", "yes"),
                                          "unknown" = "unk"),
          reinfection_case = fct_collapse(reinfection_case,
                                          "no" = c("n"),
                                          "yes" = c("y"),
                                          "unknown" = "unk"),
          test_date = ymd(test_date),
          inv_start_date = ymd(inv_start_date),
          age_group3 = factor(age_group3,
                              levels = c("0 to 4", "5 to 13", "14 to 17", 
                                     "18 to 24", "25 to 29", 
                                     "30 to 39", "40 to 49", "50 to 59", 
                                     "60 to 69", "70 to 79", "80+"),
                              labels = c("0 to 4", "5 to 13", "14 to 17", 
                                     "18 to 24", "25 to 29", 
                                     "30 to 39", "40 to 49", "50 to 59", 
                                     "60 to 69", "70 to 79", "80+"))) %>% 
   select(-time, -time2, -ever_hosp)
   

summary(covid_clean)
```

```{r}
# Save data
file_path <- c("C:/R/covid19/")


write_rds(covid_clean, paste0(file_path, "covid_data_clean.rds"))
```

# clean up variant/breakthrough/reinfection report data
```{r}
input_path <- c("C:/R/covid19/")
covid_data <- read_rds(paste0(input_path, "covid_data_clean.rds")) %>% 
   select(-age, -sex, -case)

input_path2 <- c("C:/Users/ethan.walker/Box/Missoula_COVID19EpiProfile_Working/")

variant_data_initial <- 
   read_xlsx(paste0(input_path2, "Breakthroughs Reinfections and Variants 9.9.2021.xlsx"), sheet = 1, 
             na = c(" ", "", "n/a")) 

summary(variant_data_initial)

variant_data_clean <- variant_data_initial %>% 
   mutate(`Case #:` = as.character(`Case #:`),
          `Reinfection Original Case #:` = as.character(`Reinfection Original Case #:`),
          row_id = as.numeric(row_number())) %>% 
   pivot_longer(cols = c(`Reinfection Original Case #:`, `Case #:`), names_to = "case_episode", 
                values_to = "case_id") %>% 
   filter(!is.na(case_id)) %>% 
   mutate(breakthrough = fct_collapse(`Vaccine Breakthrough?`,
                                      no = c("no", "No"),
                                      yes = c("yes", "Yes")),
          sex = fct_collapse(`Sex:`,
                             female = c("f", "F"),
                             male = c("m", "M")),
          reinfect_breakthrough = factor(`Reinfection AND Breakthrough`,
                                         levels = c("FALSE", "TRUE"),
                                         labels = c("no", "yes")),
          variant = factor(`Variant:`,
                           levels = c("B.1.1.7", "B.1.427", "B.1.429", "B.1.525", 
                                      "B.1.526", "B.1.617.2", "P.1"),
                           labels = c("Alpha", "B.1.427", "B.1.429", "Eta", 
                                      "Iota", "Delta", "Gamma")),
          variant = as.character(variant),
          variant = if_else(is.na(variant), "None listed", variant),
          variant = as.factor(variant),
          variant_classification = factor(`Variant of Concern Or Interest?`,
                                          labels = c("Variant of Concern",
                                                     "Variant of Interest")),
          age = as.numeric(`Age:`),
          followup_status = as.factor(`Follow Up Status:`),
          case_episode = factor(case_episode,
                                levels = c("Case #:", "Reinfection Original Case #:"),
                                labels = c("Case #", "Reinfect Original Case #")),
          case_episode2 = factor(case_episode,
                                levels = c("Case #", "Reinfect Original Case #"),
                                labels = c("Episode 2", "Episode 1")),
          case_id = as.factor(case_id),
          case = 1) %>% 
   select(row_id, age, followup_status, case_episode:case) %>% 
   arrange(row_id) %>% 
   #filter(case_episode == "Case #:")
   left_join(covid_data, by = "case_id")

summary(variant_data_clean)


file_path <- c("C:/R/covid19/")
write_rds(variant_data_clean, paste0(file_path, "variant_data_clean.rds"))
```

