---
title: "MCCHD Covid-19 initial data cleaning"
author: "Ethan Walker"
date: "Started 2 April 2020, Updated 21 Oct 2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(plotly)
library(knitr)
```


```{r}
# Load data and format columns

input_path <- c("C:/Users/ethan.walker/Box/Missoula_COVID19EpiProfile_Working/")


covid_data_initial <- 
   read_xlsx(paste0(input_path, "COVID data 10.21.20.xlsx"), sheet = 1,
             range = "A2:AA2000", 
                        col_names = c("case_id", "case_status", "um_case", "age", "gender", "race", 
                                      "ethnicity", "zipcode", "healthcare_worker",
                                      "symptoms", "symptom_type", "symptom_onset_date",
                                      "test_date", "contact_with_case", "contact_case_number", 
                                      "epi_linked", "epi_linked_number", "travel_hx",
                                      "hospitalized", "ventilated", "discharge_date",
                                      "chronic_conditions", "chronic_conditions_type",
                                      "number_contacts", "patient_died", 
                                      "suspected_source", "community_spread"),
                        col_types = c("text", "text", "text", "text", "text", "text",
                                      "text", "text", "text",
                                      "text", "text", "date",
                                      "date", "text", "text",
                                      "text", "text", "text",
                                      "text", "text", "date",
                                      "text", "text", 
                                      "text", "text",
                                      "text", "text"))
```


```{r}
# Clean data

covid_clean <- covid_data_initial %>% 
   filter(!is.na(case_id)) %>% 
   mutate(age = as.numeric(age),
          age_group = cut(age, breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 110),
                          labels = c("0 to 9, 0.1", "10 to 19, 0.12", "20 to 29, 0.19", 
                                     "30 to 39, 0.14", "40 to 49, 0.12", "50 to 59, 0.11", 
                                     "60 to 69, 0.11", "70 to 79, 0.07", "80+, 0.03"), right = FALSE),
          age_group2 = cut(age, breaks = c(0, 18, 65, 110),
                          labels = c("<18", "18 to 64", "65+"), right = FALSE),
          age_group3 = cut(age, breaks = c(0, 10, 15, 19, 25, 30, 40, 50, 60, 70, 80, 110),
                          labels = c("0 to 9", "10 to 14", "15 to 18", "19 to 24", "25 to 29", 
                                     "30 to 39", "40 to 49", "50 to 59", 
                                     "60 to 69", "70 to 79", "80+"), right = FALSE)) %>% 
   separate(age_group, c("age_group", "age_group_percent"), sep = ", ") %>% 
   mutate(age_group_percent = as.numeric(age_group_percent),
          county_pop = as.numeric(119000)) %>% 
   select(case_id, case_status, um_case, age, age_group, age_group_percent, age_group2, age_group3,
          county_pop, gender:community_spread) %>% 
   mutate_if(is.character, tolower) %>% 
   mutate_if(is.factor, tolower) %>% 
   mutate(symptom_fever_chill = grepl("FEVER|CHILL|CHILLS|NIGHT SWEAT", symptom_type, ignore.case = TRUE),
          symptom_cough = grepl("COUGH|MILD COUGH", symptom_type, ignore.case = TRUE),
          symptom_sob = grepl("SOB|SHORTNESS OF BREATH|BREATH|BREATHING|WINDED", symptom_type, ignore.case = TRUE),
          symptom_fatigue_lethargy = grepl("FATIGUE|LETHARGY|MALAISE|TIRED", symptom_type, ignore.case = TRUE),
          symptom_body_aches = grepl("BODY ACHES|ACHES|ACHINESS|MYALGIA|ACHE|MUSCLE ACHE", symptom_type, ignore.case = TRUE),
          symptom_headache = grepl("HEADACHE|HA|H/A", symptom_type, ignore.case = TRUE),
          symptom_taste_smell = grepl("TASTE|SMELL", symptom_type, ignore.case = TRUE),
          symptom_sorethroat = grepl("SORE THROAT|SCRATCHY THROAT|THROAT", symptom_type, ignore.case = TRUE),
          symptom_congestion = grepl("CONGESTION|RUNNY NOSE|SNEEZING|RHINORRHEA|SINUS|NOSE", symptom_type, ignore.case = TRUE),
          symptom_nv = grepl("NAUSEA|N/V|N/V/D|VOMITING", symptom_type, ignore.case = TRUE),
          symptom_diarrhea = grepl("DIARRHEA|ABDOMINAL|STOMACH|GI", symptom_type, ignore.case = TRUE),
          symptom_chest_pain = grepl("CHEST PAIN|CHEST TIGHTNESS|CHEST", symptom_type, ignore.case = TRUE)) %>% 
   separate(healthcare_worker, c("healthcare_worker", "healthcare_worker_comment"), sep = " ") %>% 
   separate(symptoms, c("symptoms", "symptoms_comment"), sep = " ") %>% 
   separate(travel_hx, c("travel_hx", "travel_hx_comment"), sep = " ") %>% 
   separate(hospitalized, c("hospitalized", "hospitalized_comment"), sep = " ") %>% 
   separate(chronic_conditions, c("chronic_conditions", "chronic_conditions_comment"), sep = "- ") %>% 
   separate(number_contacts, c("number_contacts", "number_contacts_comment"), sep = " ") %>% 
   replace_with_na_all(condition = ~.x %in% c("n/a", "na", "unknown", "unkown")) %>% 
   mutate(symptom_onset_date = as.character(symptom_onset_date),
          test_date = as.character(test_date),
          symptom_onset_date = if_else(symptom_onset_date > Sys.Date(), "NA", symptom_onset_date),
          test_date = if_else(test_date > Sys.Date(), "NA", test_date),
          symptom_onset_date = ymd(symptom_onset_date),
          discharge_date = ymd(discharge_date),
          test_date = ymd(test_date),
          number_contacts = as.numeric(number_contacts),
          number_contacts_categorical = cut(number_contacts, breaks = c(0, 5, 10, 50),
                                            labels = c("0 to 5", "5 to 10", "10+"),
                                            right = FALSE)) %>% 
   mutate(case = 1,
          gender = fct_collapse(gender, "Male" = c("m", "male"), "Female" = c("f", "female")),
          ventilated = fct_collapse(ventilated, "No" = c("n", "no"), "Yes" = c("y", "yes")),
          symptoms = fct_collapse(symptoms, "No" = c("n", "no"), "Yes" = c("y", "yes"),
                                  "N/A" = c("n/a", "cost", 44013)),
          contact_with_case = if_else(is.na(contact_with_case), "Unknown", contact_with_case),
          contact_with_case = fct_collapse(contact_with_case,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no"),
                                           "Unknown" = "Unknown"),
          contact_with_case = factor(contact_with_case,
                                     levels = c("Yes", "No", "Unknown")),
          healthcare_worker = fct_collapse(healthcare_worker,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no")),
          travel_hx = fct_collapse(travel_hx,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no")),
          hospitalized = fct_collapse(hospitalized,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no")),
          ventilated = fct_collapse(ventilated,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no"),
                                           "N/A" = c("N/A", 26, 4)),
          patient_died = fct_collapse(patient_died,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no"),
                                           "N/A" = c("wa")),
          chronic_conditions = if_else(!is.na(chronic_conditions_type), "y", "n"),
          chronic_conditions = factor(chronic_conditions, 
                                      levels = c("y", "n"),
                                      labels = c("Yes", "No")),
          community_spread = fct_collapse(community_spread,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no"),
                                           "N/A" = c("contact to case #44")),
          community_spread_new = if_else(travel_hx == "No" & contact_with_case == "No", "Yes", "No"),
          community_spread_new = factor(community_spread_new, levels = c("Yes", "No")),
          epi_linked = fct_collapse(epi_linked,
                                           "Yes" = c("y", "yes"),
                                           "No" = c("n", "no"),
                                           "N/A" = c(12, 4, 8))) %>% 
   replace_with_na(replace = list(symptoms = "N/A")) %>% 
   replace_with_na(replace = list(ventilated = "N/A")) %>% 
   replace_with_na(replace = list(patient_died = "N/A")) %>%
   replace_with_na(replace = list(epi_linked = "N/A")) %>%
   replace_with_na(replace = list(community_spread = "N/A")) %>%
   mutate(symptom_test_diff = as.duration(interval(symptom_onset_date, test_date)),
          symptom_test_diff = as.numeric(symptom_test_diff)/86400,
          symptom_test_diff = if_else(symptom_test_diff < -10, 0, symptom_test_diff),
          mean_symptom_test_diff = mean(symptom_test_diff, na.rm = TRUE),
          symptom_onset_date_new = if_else(is.na(symptom_onset_date), 
                                       test_date - mean_symptom_test_diff,
                                       symptom_onset_date),
          symptom_onset_date_new = if_else(symptoms != "No" & !is.na(symptoms), test_date,
                                           symptom_onset_date_new),
          symptom_onset_date_new = ymd(symptom_onset_date_new),
          symptom_onset_date_indicator = if_else(is.na(symptom_onset_date),
                                                 "Symptomatic: onset date estimated by test date",
                                                 "Symptomatic: onset date by self-report"),
          symptom_onset_date_indicator = if_else(symptoms == "No" & !is.na(symptoms),
                                                 "Asymptomatic: test date",
                                                 symptom_onset_date_indicator),
          symptom_onset_date_indicator = as.factor(symptom_onset_date_indicator),
          test_date_new = if_else(is.na(test_date), symptom_onset_date,
                                           test_date),
          test_date_new = ymd(test_date_new),
          test_date_indicator = if_else(is.na(test_date),
                                                 "Date of symptom onset",
                                                 "Date of test result"),
          test_date_indicator = as.factor(test_date_indicator),
          travel_hx = as.character(travel_hx),
          travel_hx = if_else(is.na(travel_hx), "Unknown", travel_hx),
          travel_hx = factor(travel_hx, levels = c("Yes", "No", "Unknown")),
          age_group = as.factor(age_group),
          age_group2 = as.factor(age_group2),
          race = factor(race,
                        levels = c("african american", "american indian or alaskan native",
                                   "asian", "native hawaiian/pacific islander", "other",
                                   "white"),
                        labels = c("african american, 0.005", "american indian or alaskan native, 0.023",
                                   "asian, 0.016", "native hawaiian/pacific islander, 0.001", "other, 0.038",
                                   "white, 0.917")),
          ethnicity = fct_collapse(ethnicity,
                                   "hispanic/latino, 0.032" = c("hispanic/latino"),
                                   "not hispanic or latino, 0.968" = 
                                    c("not hispanic or latino", "non hispanic",
                                      "not hispanic/latino", "nonhispanic"))) %>% 
   separate(race, c("race", "race_percent"), sep = ", ") %>% 
   separate(ethnicity, c("ethnicity", "ethnicity_percent"), sep = ", ") %>% 
   mutate(race = as.factor(race),
          ethnicity = as.factor(ethnicity),
          um_case = as.factor(um_case),
          case_status = as.factor(case_status))

summary(covid_clean)
```

```{r}
# Save data
file_path <- c("C:/R/covid19/")


write_rds(covid_clean, paste0(file_path, "covid_data_clean.rds"))
```

