---
title: "Missoula County COVID-19 R and Projections"
author: "Ethan Walker, University of Montana"
date: "Data as of July 30, 2020"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty, font={Large, bf}]{caption}
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 6)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(eeptools)
library(knitr)
library(incidence)
library(EpiEstim)
library(earlyR)
library(projections)
library(distcrete)
library(epitrix)
library(jsonlite)
library(httr)
library(rlist)
library(Rsftp)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7", "#999999", "#33CC99")
```


```{r}
# Load data
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

covid_data <- read_rds(paste0(file_path, "Output/covid_data_clean.rds"))
```


```{r}
## Missoula county results
# Format analysis data
inc_data <- covid_data %>% 
   filter(symptom_onset_date > "2020-05-30" & symptom_onset_date < Sys.Date() - 21) 

missoula_inc_data <- incidence(inc_data$symptom_onset_date_new)

serial_interval_mean <- 6.3
serial_interval_sd <- 5.4

r_results <- get_R(missoula_inc_data, 
                   si_mean = serial_interval_mean,
                   si_sd = serial_interval_sd)
plot(r_results)

fit_results <- incidence::fit(missoula_inc_data)

#doubling_time <- round(fit_results$info$doubling)

mu <- 6.3
sigma <- 5.4
cv <- sigma / mu
params <- gamma_mucv2shapescale(mu, cv)
si <- distcrete("gamma", shape = params$shape,
                scale = params$scale,
                interval = 1, w = 0.5)

pred_1 <- project(missoula_inc_data, R = 1.18, si = si, n_days = 30, n_sim = 1000)

plot(pred_1) +
  theme_bw()

plot_data <- covid_data %>% 
   filter(symptom_onset_date > "2020-05-30") 

plot_inc_data <- incidence(plot_data$symptom_onset_date_new)

plot(plot_inc_data, alpha = 0.5) %>%
  add_projections(pred_1, boxplots = FALSE, quantiles = c(0.025, 0.5)) +
  scale_x_date(breaks = seq.Date(from = as.Date("2020-06-01"), 
                                    to = as.Date(Sys.Date() + 8), 
                                    by = "2 days"),
                  labels = seq.Date(from = as.Date("2020-06-01"), 
                                    to = as.Date(Sys.Date() + 8), 
                                    by = "2 days"),
                  date_labels = "%d-%b") +
  theme_minimal() +
  labs(title = "COVID-19 Daily Incidence Projections, Missoula County") +
  theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.position = "right",
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank())

ggsave("C:/R/covid19/missoula_projections.png", width = 10, height = 6)
```

```{r}
county_n <- as.data.frame(missoula_inc_data$dates)
time_var <- nrow(county_n)
time_start <- seq(2, time_var-13)
time_end <- time_start + 13

estimate_results <- estimate_R(missoula_inc_data, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd,
                                                      t_start =  time_start,
                                                      t_end = time_end)))

colomns <- c(1:4, 8)
county_r <- (estimate_results$R[,colomns]) %>% 
   mutate(label = "14-day R-value") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

county_dates <- as.data.frame(estimate_results$dates)
county_i <- as.data.frame(estimate_results$I)
county_cil <- as.data.frame(estimate_results$R$`Quantile.0.025(R)`)
county_cih <- as.data.frame(estimate_results$R$`Quantile.0.975(R)`)
county_dates_new <- cbind(county_dates, county_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
county_dates_new <- county_dates_new[-(1:14), 1:2]
county_dates_new <- cbind(county_dates_new, county_cil, county_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
county_r_clean <- cbind(county_r, county_dates_new)
   

estimate_plots <- estimate_R_plots(estimate_results, what = "R")
estimate_plots

par(mar=c(4.5,4.5,6,2))
plot(r_results)


missoula_r_plot <- county_r_clean %>% 
   filter(dates > Sys.Date() - 35) %>% 
   ggplot() +
   geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
   geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
   geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
   labs(title = "COVID-19 Rolling 14-day R-values, Missoula County, 2020",
        color = "") +
   ylab("R-value") +
   xlab("") +
   geom_hline(yintercept = 1, color = "red", size = 1.2) +
   scale_x_date(date_breaks = "1 days", date_labels = "%d-%b") +
   #scale_y_continuous(breaks = seq(0, 10, 0.5), labels = seq(0, 10, 0.5)) +
   theme_minimal() +
   theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 12, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 12, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 12, colour = "black"),
         legend.text = element_text(size = 12, colour = "black"),
         axis.title.y = element_text(size = 12, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 12, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = c("black")) 
missoula_r_plot
#ggsave("C:/R/covid19/missoula_r_plot.png", width = 10, height = 8)

```

