---
title: "Missoula County COVID-19 Cases"
date: "Data as of January 31, 2022"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty, font={Large, bf}]{caption}
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 6)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
library(ggthemes)
library(knitr)
library(kableExtra)
library(gmodels)
library(incidence)
library(EpiEstim)
library(viridis)
library(ggthemes)
library(epitools)
```


```{r}
# Load data
input_path <- c("C:/R/covid19/")

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")


covid_data <- read_rds(paste0(input_path, "covid_data_clean.rds")) 

jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#CC6633",
               "#0072B2", "#D55E00", "#CC79A7", "#999999")
colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", 
                        "#44AA99", "#999933", "#882255", "Black", "#661100", 
                        "#6699CC", "#AA4499", "#888888")
```

```{r, include=FALSE, eval=FALSE}
# Check doubling time

inc_data <- covid_data %>% 
   rename(dates = test_date) %>% 
   filter(!is.na(dates)) %>% 
   filter(dates > Sys.Date() - 42 & dates < Sys.Date() - 14) %>% 
   arrange(dates) %>% 
   select(dates, case) %>% 
   group_by(dates) %>% 
   mutate(total_cases = sum(case, na.rm = TRUE)) %>% 
   arrange(dates) %>% 
   ungroup()

inc_data2 <- incidence(inc_data$dates)

plot(inc_data2)

inc_fit <- fit(inc_data2)
inc_fit
inc_fit$info$doubling # doubling time to report to D'Shane

#plot(inc_fit)

#find_peak(inc_data2)
```


```{r}
# Incidence data
age_incidence <- covid_data %>% 
   select(case, age_group, age_group_percent, county_pop) %>% 
   mutate(total_cases = n()) %>% 
   group_by(age_group) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = age_group_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(age_group, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, age_group, group_cases, group_pop, group_inc, 
          county_pop, age_group_percent) %>% 
   filter(!is.na(age_group)) %>% 
   arrange(age_group)

age_incidence2 <- covid_data %>% 
   select(case, age_group3, age_group3_percent, county_pop) %>% 
   mutate(total_cases = n()) %>% 
   group_by(age_group3) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = age_group3_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(age_group3, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, age_group3, group_cases, group_pop, group_inc, 
          county_pop, age_group3_percent) %>% 
   filter(!is.na(age_group3)) %>% 
   arrange(age_group3)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group))
age_cases <- sum(age_n$case)

# Age group bar plot - counts
age_count_plot <- covid_data %>% 
   filter(!is.na(age_group)) %>% 
   mutate(age_group = as.character(age_group),
          age_group = if_else(is.na(age_group), "Unknown", age_group),
          age_group = as.factor(age_group)) %>% 
   ggplot() +   
     geom_bar(aes(fct_rev(age_group)), fill = "steelblue", width = .6) +   
     labs(title = "COVID-19 Cases by age group",
          subtitle = paste0("Missoula County, since March 2020. N = ", age_cases, " cases."), 
          y = "Number of cases", x = "Age Group (years)") +
     scale_y_continuous(breaks = c(seq(0, 10000, 200)), labels = c(seq(0, 10000, 200))) +
     coord_flip() +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 14, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 14, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black")) 
age_count_plot

#ggsave("age_count_plot.jpg", width = 12, height = 6)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group) & !is.na(test_date)) %>% 
   filter(test_date > "2021-08-31")
age_cases <- sum(age_n$case)

# Age group line plot - counts by month
age_count_month_plot <- covid_data %>% 
   filter(test_date > "2021-08-31" & test_date < Sys.Date()) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   group_by(age_group, week_of_year) %>% 
   mutate(group_cases = n()) %>% 
   filter(!is.na(age_group)) %>% 
   filter(!is.na(week_of_year)) %>% 
   distinct(age_group, week_of_year, .keep_all = TRUE) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_line(aes(week_of_year, group_cases, group = age_group, 
                    color = age_group), size = 1.5) +
      geom_label(aes(x = Sys.Date()-14, y = 275, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      theme_minimal() +
      labs(title = "Weekly COVID-19 cases by age group",
        subtitle = paste0("Missoula County, 2021. N = ", age_cases, " cases."),
        color = "Age group") +
      ylab("Number of cases per week") +
      xlab("") +
      scale_x_date(breaks = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  labels = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 500, 25)), labels = c(seq(0, 500, 25))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

age_count_month_plot

#ggsave("C:/R/covid19/age_count_month_plot.png", width = 12, height = 6)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group3) & !is.na(test_date)) %>% 
   filter(test_date > "2021-08-31") %>% 
   filter(age < 30)
age_cases <- sum(age_n$case)

# Age group line plot - counts by month
age_count_month_plot2 <- covid_data %>% 
   filter(test_date > "2021-08-31" & test_date < Sys.Date()) %>% 
   filter(age < 30) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   group_by(age_group3, week_of_year) %>% 
   mutate(group_cases = n()) %>% 
   filter(!is.na(age_group3)) %>% 
   filter(!is.na(week_of_year)) %>% 
   distinct(age_group3, week_of_year, .keep_all = TRUE) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_line(aes(week_of_year, group_cases, group = age_group3, 
                    color = age_group3), size = 1.5) +
      geom_label(aes(x = Sys.Date()-14, y = 175, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      theme_minimal() +
      labs(title = "Weekly COVID-19 cases by age group",
        subtitle = paste0("Missoula County, 2021. N = ", age_cases, " cases."),
        color = "Age group") +
      ylab("Number of cases per week") +
      xlab("") +
      scale_x_date(breaks = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  labels = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 500, 25)), labels = c(seq(0, 500, 25))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

age_count_month_plot2

#table(age_count_month_plot2$month_of_year, age_count_month_plot2$age_group3)

#ggsave("C:/R/covid19/age_count_month_plot2.png", width = 12, height = 6)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group))
age_cases <- sum(age_n$case)

# Incidence bar plot by age
age_incidence_plot_bar <- age_incidence %>% 
   filter(region == "Missoula County") %>% 
   ggplot() +
     geom_col(aes(fct_rev(age_group), group_inc), fill = "steelblue", width = .6) +
     coord_flip() +
     labs(title = "COVID-19 incidence by age group",
          subtitle = paste0("Missoula County, since March 2020. N = ", age_cases, " cases."),
          y = "Incidence per 100,000 Population", x = "Age Group (years)") +
     scale_y_continuous(breaks = c(seq(0, 30000, 1000)), labels = c(seq(0, 30000, 1000))) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 14, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 14, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black")) 
age_incidence_plot_bar

#ggsave("age_incidence_plot_bar.jpg", width = 12, height = 6)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group) & !is.na(test_date)) %>% 
   filter(test_date > "2021-08-31")
age_cases <- sum(age_n$case)

# Incidence line plot by age and month
age_incidence_plot_line <- covid_data %>% 
   filter(test_date > "2021-08-31" & test_date < Sys.Date()) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   select(case, age_group, age_group_percent, county_pop, week_of_year) %>% 
   mutate(total_cases = n()) %>% 
   group_by(age_group, week_of_year) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = age_group_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(age_group, week_of_year, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, age_group, week_of_year, group_cases, group_prop, group_inc, 
          county_pop, age_group_percent) %>% 
   filter(!is.na(age_group)) %>% 
   arrange(age_group, week_of_year) %>% 
   filter(!is.na(week_of_year)) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_line(aes(week_of_year, group_inc, group = age_group, 
                    color = age_group), size = 1.5) +
      theme_minimal() +
      labs(title = "COVID-19 incidence per week by age group",
        subtitle = paste0("Missoula County, 2021. N = ", age_cases, " cases."),
        color = "Age group") +
      ylab("Incidence per 100,000") +
      xlab("") +
      geom_label(aes(x = Sys.Date()-14, y = 1300, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      scale_x_date(breaks = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  labels = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 3000, 200)), labels = c(seq(0, 3000, 200))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

age_incidence_plot_line

#ggsave("C:/R/covid19/age_incidence_plot_line.png", width = 12, height = 6)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group) & !is.na(test_date)) %>% 
   filter(test_date > "2021-08-31") %>% 
   filter(age < 30)
age_cases <- sum(age_n$case)

# Incidence line plot by age and month
age_incidence_plot_line <- covid_data %>% 
   filter(test_date > "2021-08-31" & test_date < Sys.Date()) %>% 
   filter(age < 30) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   select(case, age_group3, age_group3_percent, county_pop, week_of_year) %>% 
   mutate(total_cases = n()) %>% 
   group_by(age_group3, week_of_year) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = age_group3_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(age_group3, week_of_year, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, age_group3, week_of_year, group_cases, group_prop, group_inc, 
          county_pop, age_group3_percent) %>% 
   filter(!is.na(age_group3)) %>% 
   arrange(age_group3, week_of_year) %>% 
   filter(!is.na(week_of_year)) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_line(aes(week_of_year, group_inc, group = age_group3, 
                    color = age_group3), size = 1.5) +
      theme_minimal() +
      labs(title = "COVID-19 incidence per week by age group",
        subtitle = paste0("Missoula County, 2021. N = ", age_cases, " cases."),
        color = "Age group") +
      ylab("Incidence per 100,000") +
      xlab("") +
      geom_label(aes(x = Sys.Date()-14, y = 1300, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      scale_x_date(breaks = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  labels = seq.Date(from = as.Date("2021-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 5000, 500)), labels = c(seq(0, 5000, 500))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

age_incidence_plot_line

#ggsave("C:/R/covid19/age_incidence_plot_line.png", width = 12, height = 6)
```

\pagebreak  

```{r, fig.width = 10, fig.height = 5}
# Epi curve - test date

plot_data <- covid_data %>% 
   filter(test_date > "2021-05-31" & test_date < Sys.Date()) 

total_cases <- sum(plot_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_test_date <- plot_data %>% 
   ggplot() +
     geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
     geom_col(aes(test_date, case), color = "steelblue") +
     geom_vline(xintercept = as.numeric(as.Date("2021-07-04")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-07-04"), label = "July 4th Holiday", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-08-30")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-08-30"), label = "Fall Semester", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-09-06")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-09-06"), label = "Labor Day", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-10-31")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-10-31"), label = "Halloween", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-11-25")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-11-25"), label = "Thanksgiving", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-12-28")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-12-28"), label = "Winter Holidays", vjust = -0.5,
                 y = 80), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_label(aes(x = Sys.Date()-14, y = 230, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
     labs(title = "COVID-19 Cases in Missoula County Since June 1, 2021",
          subtitle = paste0("Cases in plot = ", total_cases),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("Test Date") +
     scale_x_date(breaks = seq.Date(from = as.Date("2021-06-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "5 days"),
                  labels = seq.Date(from = as.Date("2021-06-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "5 days"),
                  date_labels = "%d-%b") + 
     scale_y_continuous(breaks = seq(0, 500, 25), labels = seq(0, 500, 25)) + 
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_fill_manual(values = cbPalette)   

epi_curve_test_date

#ggsave("mc_epi_curve_test_date.jpg", width = 12, height = 5.5)
```

\pagebreak  

```{r}
## Missoula county R results using county data
## Using State data to be able to incorporate local vs imported cases
## Only updates once per week

case_data <- covid_data %>% 
   rename(dates = test_date) %>% 
   filter(!is.na(dates)) %>% 
   filter(dates > "2021-05-31" & dates < Sys.Date() - 13) %>% 
   arrange(dates) %>% 
   select(dates, case) %>% 
   arrange(dates) %>% 
   ungroup() 

latest_date <- format(Sys.Date() - 14, "%Y-%m-%d")

incidence_data <- incidence(case_data$dates, last_date = latest_date)

# Set dates for 14-day rolling averages
county_n <- as.data.frame(incidence_data$dates)
time_var <- nrow(county_n)
time_start <- seq(2, time_var-13)
time_end <- time_start + 13


# Serial Interval derived from State of Montana paired case data
serial_interval_mean <- 4.42
serial_interval_sd <- 3.51

r_results <- estimate_R(incidence_data, method="parametric_si", 
                           config = make_config(list(mean_si = serial_interval_mean, 
                                                     std_si = serial_interval_sd,
                                                     t_start =  time_start,
                                                     t_end = time_end)))

# Format and save analysis results
colomns <- c(1:4, 8)
county_r <- (r_results$R[,colomns]) %>% 
   mutate(region = "Missoula County") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

county_dates <- as.data.frame(r_results$dates)
county_i <- as.data.frame(r_results$I)
county_cil <- as.data.frame(r_results$R$`Quantile.0.025(R)`)
county_cih <- as.data.frame(r_results$R$`Quantile.0.975(R)`)
county_dates_new <- cbind(county_dates, county_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
county_dates_new <- county_dates_new[-(1:14), 1:2]
county_dates_new <- cbind(county_dates_new, county_cil, county_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
county_r <- cbind(county_r, county_dates_new)


county_r_plot <- county_r %>% 
   filter(dates > "2021-05-31") %>% 
   ggplot() +
   geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
   #geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
   #geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
   labs(title = "COVID-19 Rolling 14-day R-number, Missoula County",
        color = "") +
   ylab("R-number") +
   xlab("") +
   geom_hline(yintercept = 1, color = "red", size = 1.2) +
   scale_x_date(date_breaks = "5 days", date_labels = "%d-%b") +
   scale_y_continuous(breaks = seq(0, 5, 0.05), labels = seq(0, 5, 0.05)) +
   theme_minimal() +
   theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = c("black")) 
county_r_plot

#ggsave("C:/R/covid19/missoula_r_plot.png", width = 12, height = 6)
```

\pagebreak  

```{r, fig.width = 11, fig.height = 5}
# Epi curve - full data since March
plot_data <- covid_data %>% 
   filter(test_date > "2020-03-01" & test_date < Sys.Date()) 

total_cases <- sum(covid_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_full <- plot_data %>% 
   filter(!is.na(test_date)) %>% 
   ggplot() +
     geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
     geom_col(aes(test_date, case), color = "steelblue") +
     geom_vline(xintercept = as.numeric(as.Date("2020-03-28")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-03-28"), label = "Shelter in place order", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-04-26")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-04-26"), label = "Phase 1 reopening", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-05-28")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-05-28"), label = "Memorial Day + Phase 2 reopening", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-09-07")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-09-07"), label = "Labor Day", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-07-06")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-07-06"), label = "July 4th + Mask Mandate", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-08-19")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-08-19"), label = "UM semester start", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-10-31")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-10-31"), label = "Halloween", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-11-26")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-11-26"), label = "Thanksgiving", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-12-28")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-12-28"), label = "Winter Holidays", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-07-04")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-07-04"), label = "July 4th Holiday", vjust = -0.5,
                 y = 130), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-09-01")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-09-01"), label = "Fall Semester + Labor Day", vjust = -0.5,
                 y = 85), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-10-31")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-10-31"), label = "Halloween", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-11-25")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-11-25"), label = "Thanksgiving", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2021-12-28")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2021-12-28"), label = "Winter Holidays", vjust = -0.5,
                 y = 80), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_label(aes(x = Sys.Date()-40, y = 230, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
     labs(title = "COVID-19 Cases in Missoula County by Date",
          subtitle = paste0("Total cases = ", total_cases),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("Test Date") +
     scale_x_date(breaks = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  labels = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  date_labels = "%d-%b-%y") +
     scale_y_continuous(breaks = seq(0, 500, 25), labels = seq(0, 500, 25)) + 
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.position = "top",
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank())  +
     scale_fill_manual(values = cbPalette) 

epi_curve_full

#ggsave("epi_curve_full.jpg", width = 12, height = 5.5)
```

\pagebreak  

```{r, fig.width = 11, fig.height = 5}
incidence_plot_line <- covid_data %>% 
   filter(test_date > "2020-03-01" & test_date < Sys.Date()) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   select(case, hospitalizations, county_pop, week_of_year, test_date) %>% 
   mutate(hosp = as.numeric(hospitalizations) - 1) %>% 
   group_by(week_of_year) %>% 
   mutate(group_cases = n(),
          case_inc = group_cases/county_pop*100000,
          group_hosp = sum(hosp),
          hosp_inc = group_hosp/county_pop*100000,
          case_hosp_ratio = group_cases/group_hosp) %>% 
   ungroup() %>% 
   distinct(week_of_year, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, week_of_year, group_cases, case_inc, test_date, hosp,
          group_hosp, hosp_inc, county_pop, case_hosp_ratio) %>% 
   arrange(week_of_year) %>% 
   filter(!is.na(week_of_year)) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_col(aes(week_of_year, case_inc), fill = "steelblue", size = 1.5) +
      #geom_line(aes(week_of_year, hosp_inc), color = "red", size = 1.5) +
      theme_minimal() +
      labs(title = "COVID-19 weekly incidence of cases") +
      ylab("Incidence per 100,000") +
      xlab("") +
      geom_label(aes(x = Sys.Date()-40, y = 800, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      scale_x_date(breaks = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  labels = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  date_labels = "%d-%b-%y") +
      scale_y_continuous(breaks = c(seq(0, 3000, 250)), labels = c(seq(0, 3000, 250))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

incidence_plot_line

#ggsave("C:/R/covid19/age_incidence_plot_line.png", width = 12, height = 6)
```


```{r, fig.width = 11, fig.height = 5}
incidence_plot_line <- covid_data %>% 
   filter(test_date > "2020-03-01" & test_date < Sys.Date()) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   select(case, hospitalizations, county_pop, week_of_year, test_date) %>% 
   mutate(hosp = as.numeric(hospitalizations) - 1) %>% 
   group_by(week_of_year) %>% 
   mutate(group_cases = n(),
          case_inc = group_cases/county_pop*100000,
          group_hosp = sum(hosp),
          hosp_inc = group_hosp/county_pop*100000,
          case_hosp_ratio = group_cases/group_hosp) %>% 
   ungroup() %>% 
   distinct(week_of_year, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, week_of_year, group_cases, case_inc, test_date, hosp,
          group_hosp, hosp_inc, county_pop, case_hosp_ratio) %>% 
   arrange(week_of_year) %>% 
   filter(!is.na(week_of_year)) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 21, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_col(aes(week_of_year, hosp_inc), fill = "red", size = 1.5) +
      #geom_line(aes(week_of_year, case_hosp_ratio), color = "black", size = 1.5) +
      theme_minimal() +
      labs(title = "COVID-19 weekly incidence of hospitalization") +
      ylab("Incidence per 100,000") +
      xlab("") +
      geom_label(aes(x = Sys.Date()-40, y = 25, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      scale_x_date(breaks = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  labels = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  date_labels = "%d-%b-%y") +
      scale_y_continuous(breaks = c(seq(0, 50, 5)), labels = c(seq(0, 50, 5))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

incidence_plot_line

#ggsave("C:/R/covid19/age_incidence_plot_line.png", width = 12, height = 6)
```


```{r, include=FALSE, eval=FALSE}
# Epi curve - test date

plot_data <- covid_data %>% 
   filter(um_case == "yes") %>% 
   filter(test_date > "2020-08-31") 

total_cases <- sum(plot_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_test_date <- plot_data %>% 
   ggplot() +
     geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
     geom_col(aes(test_date, case), color = "steelblue") +
     geom_vline(xintercept = as.numeric(as.Date("2020-09-07")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-09-07"), label = "Labor Day", vjust = -0.5,
                 y = 12), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-10-31")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-10-31"), label = "Halloween", vjust = -0.5,
                 y = 12), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-11-26")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-11-26"), label = "Thanksgiving", vjust = -0.5,
                 y = 12), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_label(aes(x = Sys.Date()-10, y = 15, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
     labs(title = "UM COVID-19 Cases Since September 1, 2020",
          subtitle = paste0("Cases in plot = ", total_cases),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("Test Date") +
     scale_x_date(breaks = seq.Date(from = as.Date("2020-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "3 days"),
                  labels = seq.Date(from = as.Date("2020-09-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "3 days"),
                  date_labels = "%d-%b") + 
     scale_y_continuous(breaks = seq(0, 50, 5), labels = seq(0, 50, 5)) + 
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_fill_manual(values = cbPalette)   

epi_curve_test_date

#ggsave("um_epi_curve_test_date.jpg", width = 12, height = 5.5)
```


```{r, include=FALSE, eval=FALSE}
total_n <- covid_data %>% 
   filter(!is.na(test_date)) %>% 
   filter(test_date > "2020-03-01")
total_cases <- sum(total_n$case)

# Incidence line plot by age and month
incidence_plot_line <- covid_data %>% 
   filter(test_date > "2020-03-01" & test_date < Sys.Date()) %>% 
   mutate(week_of_year = cut.Date(test_date, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year),
          hospitalizations = if_else(hospitalizations == "yes", 1, 0)) %>% 
   select(case, county_pop, week_of_year, hospitalizations) %>% 
   mutate(total_cases = n()) %>% 
   group_by(week_of_year) %>% 
   mutate(group_cases = n(),
          group_hosp = sum(hospitalizations),
          group_inc = group_cases/county_pop*100000,
          hosp_inc = group_hosp/county_pop*100000) %>% 
   ungroup() %>% 
   distinct(week_of_year, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, week_of_year, group_cases, group_inc, county_pop, hosp_inc, group_hosp) %>% 
   arrange(week_of_year) %>% 
   filter(!is.na(week_of_year)) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      #geom_line(aes(week_of_year, group_inc), size = 1.5) +
      geom_line(aes(week_of_year, hosp_inc), size = 1.5, color = "red") +
      theme_minimal() +
      labs(title = "COVID-19 hospitalization incidence per week",
        subtitle = paste0("Missoula County, N = ", total_cases, " cases.")) +
      ylab("Incidence per 100,000") +
      xlab("") +
      scale_x_date(breaks = seq.Date(from = as.Date("2020-03-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  labels = seq.Date(from = as.Date("2020-03-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "14 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 25, 2)), labels = c(seq(0, 25, 2))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) 

incidence_plot_line

#ggsave("C:/R/covid19/age_incidence_plot_line.png", width = 12, height = 6)
```



