---
title: "Missoula County COVID-19 Report"
author: "Ethan Walker, University of Montana"
date: "Data as of November 13, 2020"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty, font={Large, bf}]{caption}
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 6)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(knitr)
library(ggthemes)
library(knitr)
library(kableExtra)
library(gmodels)
library(incidence)
library(EpiEstim)
library(viridis)
library(ggthemes)
library(epitools)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#CC6633",
               "#0072B2", "#D55E00", "#CC79A7", "#999999")
colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                        "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")
```


```{r}
# Load data
input_path <- c("C:/R/covid19/")
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")


covid_data <- read_rds(paste0(input_path, "covid_data_clean.rds")) 
```


```{r}
# Incidence table

overall_summary <- covid_data %>% 
   mutate(total_cases = n()) %>% 
   summarize("Number of Cases" = n()) %>% 
   mutate("Proportion of Cases (%)" = 
          round(`Number of Cases`/(sum(`Number of Cases`))*100),
          "Incidence per 100,000 Population" = 
          round(`Number of Cases`/119600*100000, digits = 1)) %>% 
   mutate("Data Category" = "Total") %>%
   na.exclude()

age_group_summary <- covid_data %>% 
   mutate(total_cases = n(),
          age_group_pop = if_else(age_group2 == "<18", 119600*0.188, 119600*0.656),
          age_group_pop = if_else(age_group2 == "65+", 119600*0.156, age_group_pop)) %>% 
   group_by(age_group2, age_group_pop) %>% 
   summarize("Number of Cases" = n()) %>% 
   ungroup() %>% 
   mutate("Proportion of Cases (%)" = 
          round(`Number of Cases`/(sum(`Number of Cases`))*100),
          "Incidence per 100,000 Population" = 
          round(`Number of Cases`/age_group_pop*100000, digits = 1)) %>% 
   rename("Data Category" = age_group2) %>% 
   select(-age_group_pop) %>% 
   na.exclude()

gender_summary <- covid_data %>% 
   mutate(total_cases = n(),
          gender_pop = if_else(gender == "Female", 119600*0.499, 119600*0.501)) %>% 
   group_by(gender, gender_pop) %>% 
   summarize("Number of Cases" = n()) %>% 
   ungroup() %>% 
   mutate("Proportion of Cases (%)" = 
          round(`Number of Cases`/(sum(`Number of Cases`))*100),
          "Incidence per 100,000 Population" = 
          round(`Number of Cases`/gender_pop*100000, digits = 1)) %>% 
   rename("Data Category" = gender) %>% 
   select(-gender_pop) %>% 
   na.exclude()

travel_summary <- covid_data %>% 
   mutate(total_cases = n()) %>% 
   group_by(travel_hx) %>% 
   summarize("Number of Cases" = n()) %>% 
   ungroup() %>% 
   mutate("Proportion of Cases (%)" = 
          round(`Number of Cases`/(sum(`Number of Cases`))*100),
          "Incidence per 100,000 Population" = "NA") %>% 
   rename("Data Category" = travel_hx) %>% 
   na.exclude()

contact_summary <- covid_data %>% 
   mutate(total_cases = n()) %>% 
   group_by(contact_with_case) %>% 
   summarize("Number of Cases" = n()) %>% 
   ungroup() %>% 
   mutate("Proportion of Cases (%)" = 
          round(`Number of Cases`/(sum(`Number of Cases`))*100),
          "Incidence per 100,000 Population" = "NA") %>% 
   rename("Data Category" = contact_with_case) %>% 
   na.exclude()

community_spread_summary <- covid_data %>% 
   mutate(total_cases = n()) %>% 
   group_by(community_spread_new) %>% 
   summarize("Number of Cases" = n()) %>% 
   ungroup() %>% 
   mutate("Proportion of Cases (%)" = 
          round(`Number of Cases`/(sum(`Number of Cases`))*100),
          "Incidence per 100,000 Population" = "NA") %>% 
   rename("Data Category" = community_spread_new) %>% 
   na.exclude()


covid_summary <- rbind(overall_summary, age_group_summary, gender_summary,
                       travel_summary, contact_summary) %>% 
   select("Data Category", "Number of Cases", 
          "Proportion of Cases (%)", "Incidence per 100,000 Population")


kable(covid_summary, caption = "Missoula County COVID-19 Cases",
      format = "latex", align = "c") %>% 
   kable_styling(font_size = 10) %>% 
   row_spec(0, bold = TRUE, font_size = 10) %>% 
   pack_rows("All Cases", 1, 1) %>% 
   pack_rows("Age Group (Years)", 2, 4) %>% 
   pack_rows("Gender", 5, 6) %>% 
   pack_rows("Travel History", 7, 9) %>% 
   pack_rows("Contact with Known Case", 10, 12) %>% 
   footnote(c("Travel History: case left Missoula County.",
     "Data is still being collected. Percentages may not add to 100% in some cases."))
```

\clearpage

```{r}
# Incidence data
age_incidence <- covid_data %>% 
   select(case, age_group, age_group_percent, county_pop) %>% 
   mutate(total_cases = n()) %>% 
   group_by(age_group) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = age_group_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(age_group, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, age_group, group_cases, group_prop, group_inc, 
          county_pop, age_group_percent) %>% 
   filter(!is.na(age_group)) %>% 
   arrange(age_group)

race_incidence <- covid_data %>% 
   select(case, race, race_percent, county_pop) %>% 
   mutate(total_cases = n(),
          race_percent = as.numeric(race_percent)) %>% 
   group_by(race) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = race_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(race, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, race, group_cases, group_prop, group_inc, 
          county_pop, race_percent) %>% 
   filter(!is.na(race)) %>% 
   arrange(race)

ethnicity_incidence <- covid_data %>% 
   select(case, ethnicity, ethnicity_percent, county_pop) %>% 
   mutate(total_cases = n(),
          ethnicity_percent = as.numeric(ethnicity_percent)) %>% 
   group_by(ethnicity) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = ethnicity_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(ethnicity, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, ethnicity, group_cases, group_prop, group_inc, 
          county_pop, ethnicity_percent) %>% 
   filter(!is.na(ethnicity)) %>% 
   arrange(ethnicity)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group))
age_cases <- sum(age_n$case)

# Age group bar plot - counts
age_count_plot <- covid_data %>% 
   filter(!is.na(age_group)) %>% 
   mutate(age_group = as.character(age_group),
          age_group = if_else(is.na(age_group), "Unknown", age_group),
          age_group = as.factor(age_group)) %>% 
   ggplot() +   
     geom_bar(aes(fct_rev(age_group)), fill = "steelblue", width = .6) +   
     labs(title = "COVID-19 Cases by age group",
          subtitle = paste0("Missoula County, since March 2020. N = ", age_cases, " cases."), 
          y = "Number of cases", x = "Age Group (years)") +
     scale_y_continuous(breaks = c(seq(0, 2000, 50)), labels = c(seq(0, 2000, 50))) +
     coord_flip() +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 14, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 14, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black")) 
age_count_plot

#ggsave("age_count_plot.jpg", width = 10, height = 5)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group) & !is.na(test_date_new))
age_cases <- sum(age_n$case)

# Age group line plot - counts by month
age_count_month_plot <- covid_data %>% 
   filter(test_date_new > "2020-08-01") %>% 
   mutate(month_of_year = month(test_date_new, label = TRUE)) %>% 
   mutate(week_of_year = cut.Date(test_date_new, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   group_by(age_group, week_of_year) %>% 
   mutate(group_cases = n()) %>% 
   filter(!is.na(age_group)) %>% 
   filter(!is.na(week_of_year)) %>% 
   distinct(age_group, week_of_year, .keep_all = TRUE) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_line(aes(week_of_year, group_cases, group = age_group, 
                    color = age_group), size = 1.5) +
      geom_label(aes(x = Sys.Date()-9, y = 90, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      theme_minimal() +
      labs(title = "Weekly COVID-19 cases by age group",
        subtitle = paste0("Missoula County, 2020. N = ", age_cases, " cases."),
        color = "Age group") +
      ylab("Number of cases per week") +
      xlab("") +
      scale_x_date(breaks = seq.Date(from = as.Date("2020-08-02"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  labels = seq.Date(from = as.Date("2020-08-02"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 200, 10)), labels = c(seq(0, 200, 10))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

age_count_month_plot

#ggsave("C:/R/covid19/age_count_month_plot.png", width = 10, height = 6)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group))
age_cases <- sum(age_n$case)

# Incidence bar plot by age
age_incidence_plot_bar <- age_incidence %>% 
   filter(region == "Missoula County") %>% 
   ggplot() +
     geom_col(aes(fct_rev(age_group), group_inc), fill = "steelblue", width = .6) +
     coord_flip() +
     labs(title = "COVID-19 incidence by age group",
          subtitle = paste0("Missoula County, since March 2020. N = ", age_cases, " cases."),
          y = "Incidence per 100,000 Population", x = "Age Group (years)") +
     scale_y_continuous(breaks = c(seq(0, 5000, 250)), labels = c(seq(0, 5000, 250))) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 14, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 14, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black")) 
age_incidence_plot_bar

#ggsave("age_incidence_plot_bar.jpg", width = 10, height = 5)
```

\pagebreak  

```{r}
age_n <- covid_data %>% 
   filter(!is.na(age_group) & !is.na(test_date_new))
age_cases <- sum(age_n$case)

# Incidence line plot by age and month
age_incidence_plot_line <- covid_data %>% 
   filter(test_date_new > "2020-08-01") %>% 
   #mutate(month_of_year = month(test_date_new, label = TRUE)) %>% 
   mutate(week_of_year = cut.Date(test_date_new, breaks = "1 week", start.on.monday = FALSE),
          week_of_year = ymd(week_of_year)) %>% 
   select(case, age_group, age_group_percent, county_pop, week_of_year) %>% 
   mutate(total_cases = n()) %>% 
   group_by(age_group, week_of_year) %>% 
   mutate(group_cases = n(),
          group_prop = group_cases/total_cases*100,
          group_pop = age_group_percent*county_pop,
          group_inc = group_cases/group_pop*100000) %>% 
   ungroup() %>% 
   distinct(age_group, week_of_year, .keep_all = TRUE) %>% 
   mutate(region = "Missoula County") %>% 
   select(region, age_group, week_of_year, group_cases, group_prop, group_inc, 
          county_pop, age_group_percent) %>% 
   filter(!is.na(age_group)) %>% 
   arrange(age_group, week_of_year) %>% 
   filter(!is.na(week_of_year)) %>% 
   ggplot() +
      geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
      geom_line(aes(week_of_year, group_inc, group = age_group, 
                    color = age_group), size = 1.5) +
      theme_minimal() +
      labs(title = "COVID-19 incidence per week by age group",
        subtitle = paste0("Missoula County, 2020. N = ", age_cases, " cases."),
        color = "Age group") +
      ylab("Incidence per 100,000") +
      xlab("") +
      geom_label(aes(x = Sys.Date()-9, y = 600, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
      scale_x_date(breaks = seq.Date(from = as.Date("2020-08-02"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  labels = seq.Date(from = as.Date("2020-08-02"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "7 days"),
                  date_labels = "%d-%b") +
      scale_y_continuous(breaks = c(seq(0, 1000, 50)), labels = c(seq(0, 1000, 50))) +
      theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = colorblind_palette)

age_incidence_plot_line

#ggsave("C:/R/covid19/age_incidence_plot_line.png", width = 10, height = 6)
```

\pagebreak  

```{r}
ethnicity_n <- covid_data %>% 
   filter(!is.na(ethnicity))
ethnicity_cases <- sum(ethnicity_n$case)

#Bar plot of ethnicity count data
ethnicity_plot <- covid_data %>% 
   filter(!is.na(ethnicity)) %>% 
   ggplot() +   
     geom_bar(aes(x = fct_rev(ethnicity)), fill = "steelblue", width = .6) +   
     labs(title = "COVID-19 cases by self-reported ethnicity",
          subtitle = paste0("Missoula County. N = ", ethnicity_cases, " cases."),
          y = "Count", x = "", fill = "") +
     scale_y_continuous(breaks = c(seq(0, 5000, 100)), labels = c(seq(0, 5000, 100))) +
     coord_flip() +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 16, colour = "white"),
           axis.title.x = element_blank(),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black")) + 
     scale_fill_manual(values = colorblind_palette)
ethnicity_plot

#ggsave("ethnicity_plot.jpg", width = 10, height = 5)
```

\pagebreak  

```{r}
#Bar plot of ethnicity incidence data
ethnicity_incidence_plot <- ethnicity_incidence %>% 
   filter(region == "Missoula County") %>% 
   ggplot() +
     geom_col(aes(fct_rev(ethnicity), group_inc), fill = "steelblue", width = .6) +
     coord_flip() +
     labs(title = "COVID-19 incidence by self-reported ethnicity",
          subtitle = paste0("Missoula County. N = ", ethnicity_cases, " cases."),
          y = "Incidence per 100,000 Population", x = "") +
     scale_y_continuous(breaks = c(seq(0, 5000, 100)), labels = c(seq(0, 5000, 100))) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 14, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 14, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black"))
ethnicity_incidence_plot

#ggsave("ethnicity_incidence_plot.jpg", width = 10, height = 5)
```

\pagebreak  

```{r}
#Symptoms and gender bar plot
symptoms_gender_plot <- covid_data %>% 
   filter(!is.na(gender)) %>% 
   pivot_longer(cols = c(symptom_fever_chill:symptom_diarrhea),
                names_to = "variable", values_to = "values") %>% 
   group_by(variable, gender) %>% 
   mutate(values = as.numeric(values),
          values = sum(values)) %>% 
   distinct(variable, .keep_all = TRUE) %>% 
   ungroup() %>% 
   arrange(gender, values) %>% 
   mutate(variable = factor(variable,
                            levels = c("symptom_fever_chill", "symptom_cough",
                                       "symptom_sob", "symptom_fatigue_lethargy",
                                       "symptom_body_aches", "symptom_headache", 
                                       "symptom_taste_smell", "symptom_sorethroat",
                                       "symptom_congestion", "symptom_nv",
                                       "symptom_diarrhea"),
                            labels = c("Fever/chills", "Cough",
                                       "Short of breath", "Fatigue",
                                       "Muscle/body aches", "Headache", 
                                       "Taste/Smell Loss", "Sore throat",
                                       "Congestion", "Nausea/vomiting",
                                       "Diarrhea"))) %>% 
   ggplot(aes(x = fct_rev(variable), y = values, fill = gender)) +   
     geom_bar(stat = "identity", width = .6) +   
     labs(title = "Symptoms reported at time of testing", 
          subtitle = "By gender, Missoula County, 2020",
          y = "Count", x = "", fill = "") +
     scale_y_continuous(breaks = c(seq(0, 2000, 100)), labels = c(seq(0, 2000, 100))) +
     coord_flip() +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 18, colour = "black"),
           panel.grid = element_blank(),
           axis.text.x = element_text(size = 14, colour = "black", 
                                     angle = 45, vjust = 0.75, hjust = 0.9),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black"),
           axis.text.y = element_text(size = 16, colour = "black"),
           axis.title.y = element_text(size = 16, colour = "white"),
           axis.title.x = element_blank(),
           axis.line.x = element_line(colour = "black", size = 1.2), 
           axis.line.y = element_line(colour = "black", size = 1.2), 
           axis.ticks = element_line(colour = "black")) + 
     scale_fill_manual(values = cbPalette)
symptoms_gender_plot

#ggsave("symptoms_gender_plot.jpg", width = 10, height = 5)
```

\pagebreak  

```{r}
piechart_function <- function(data = covid_data, plot_fill, var_label) {

chart_data <- data %>% 
   rename(chart_var = plot_fill) %>% 
   filter(!is.na(chart_var)) %>% 
   mutate(total_n = n()) %>% 
   group_by(chart_var, total_n) %>% 
   mutate(group_n = n()) %>% 
   distinct(group_n) %>% 
   mutate(group_percent = round(group_n/total_n*100),
          right_par = " (",
          left_par = "%)") %>% 
   ungroup() %>% 
   unite(group_lab, c("group_n", "right_par", "group_percent", "left_par"), sep = "", remove = FALSE)
   
covid_piechart <- chart_data %>% 
   ggplot(aes("", group_n, fill = chart_var)) +
     geom_bar(stat = "identity", color = "black", width = 1) +
     coord_polar("y") +
     geom_text(aes(label = group_lab), 
               position = position_stack(vjust = 0.5),
               color = "white", size = 6) +
     labs(title = "Missoula County COVID-19 cases", fill = "",
          subtitle = var_label) + 
     theme_void() +
     theme(title = element_text(size = 16, colour = "black"),
           legend.text = element_text(size = 16, colour = "black"),
           legend.title = element_text(size = 16, colour = "black")) +
           scale_fill_manual(values = colorblind_palette)
covid_piechart

}
```


```{r}
piechart_function(plot_fill = "number_contacts_categorical", var_label = "Number of contacts - all cases")

#ggsave("piechart_contacts.jpg", width = 10, height = 5)
```

\pagebreak  

```{r, fig.width = 11, fig.height = 5}
# Epi curve - date of onset - recent data

plot_data <- covid_data %>% 
   filter(symptom_onset_date_new > "2020-07-31") 

total_cases <- sum(plot_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_onset_recent <- plot_data %>% 
   group_by(symptom_onset_date_new) %>% 
   ggplot() +
     geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
     geom_col(aes(symptom_onset_date_new, case, fill = symptom_onset_date_indicator)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-09-07")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-09-07"), label = "Labor Day", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-08-19")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-08-19"), label = "UM semester start", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_label(aes(x = Sys.Date()-8, y = 120, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
     labs(title = "COVID-19 Cases in Missoula County Since August 1, 2020",
          subtitle = paste0("Cases in plot = ", total_cases),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(breaks = seq.Date(from = as.Date("2020-08-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "3 days"),
                  labels = seq.Date(from = as.Date("2020-08-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "3 days"),
                  date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.position = "top",
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank())  +
     scale_fill_manual(values = cbPalette) 
epi_curve_onset_recent 

#ggsave("ep_curve_onset_recent.jpg", width = 12, height = 5.5)
```

\pagebreak  

```{r, fig.width = 10, fig.height = 5}
# Epi curve - test date

plot_data <- covid_data %>% 
   filter(test_date_new > "2020-07-31") 

total_cases <- sum(plot_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_test_date <- plot_data %>% 
   ggplot() +
     geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
     geom_col(aes(test_date_new, case, fill = test_date_indicator)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-09-07")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-09-07"), label = "Labor Day", vjust = -0.5,
                 y = 60), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-08-19")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-08-19"), label = "UM semester start", vjust = -0.5,
                 y = 60), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_label(aes(x = Sys.Date()-8, y = 75, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
     labs(title = "COVID-19 Cases in Missoula County Since August 1, 2020",
          subtitle = paste0("Cases in plot = ", total_cases),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(breaks = seq.Date(from = as.Date("2020-08-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "3 days"),
                  labels = seq.Date(from = as.Date("2020-08-01"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "3 days"),
                  date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.position = "top",
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_fill_manual(values = cbPalette)   

epi_curve_test_date

#ggsave("epi_curve_test_date.jpg", width = 12, height = 5.5)
```

\pagebreak  

```{r}
## Missoula county R results using county data
## Using State data to be able to incorporate local vs imported cases
## Only updates once per week

case_data <- covid_data %>% 
   rename(dates = symptom_onset_date_new) %>% 
   mutate(local = if_else(suspected_source != "travel" | is.na(suspected_source), 1, 0),
          imported = if_else(suspected_source == "travel", 1, 0)) %>% 
   filter(!is.na(dates)) %>% 
   filter(dates > "2020-06-30" & dates < Sys.Date() - 13) %>% 
   arrange(dates) %>% 
   select(dates, local, imported, case) %>% 
   group_by(dates) %>% 
   mutate(local = sum(local, na.rm = TRUE),
          imported = sum(imported, na.rm = TRUE),
          total_cases = sum(case, na.rm = TRUE)) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   arrange(dates) %>% 
   ungroup() 


case_data_2 <- case_data %>% 
   mutate(I = local + imported) %>% 
   select(dates, I) 

latest_date <- format(Sys.Date() - 14, "%Y-%m-%d")

incidence_data <- incidence(case_data_2$dates, last_date = latest_date)

li_inc_data <- as.data.frame(incidence_data$dates) %>% 
   mutate(dates = ymd(incidence_data$dates)) %>% 
   select(dates) %>% 
   left_join(case_data, by = "dates") %>% 
   mutate(local = if_else(is.na(local), 0, local),
          imported = if_else(is.na(imported), 0, imported)) %>% 
   select(-case, -total_cases)


# Set dates for 14-day rolling averages
county_n <- as.data.frame(li_inc_data$dates)
time_var <- nrow(county_n)
time_start <- seq(2, time_var-13)
time_end <- time_start + 13


# Serial Interval derived from State of Montana paired case data
serial_interval_mean <- 5.29
serial_interval_sd <- 4.45

r_results <- estimate_R(li_inc_data, method="parametric_si", 
                           config = make_config(list(mean_si = serial_interval_mean, 
                                                     std_si = serial_interval_sd,
                                                     t_start =  time_start,
                                                     t_end = time_end)))

# Format and save analysis results
colomns <- c(1:4, 8)
county_r <- (r_results$R[,colomns]) %>% 
   mutate(region = "Missoula County") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

county_dates <- as.data.frame(r_results$dates)
county_i <- as.data.frame(r_results$I)
county_cil <- as.data.frame(r_results$R$`Quantile.0.025(R)`)
county_cih <- as.data.frame(r_results$R$`Quantile.0.975(R)`)
county_dates_new <- cbind(county_dates, county_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
county_dates_new <- county_dates_new[-(1:14), 1:2]
county_dates_new <- cbind(county_dates_new, county_cil, county_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
county_r <- cbind(county_r, county_dates_new)


county_r_plot <- county_r %>% 
   filter(dates > "2020-07-31") %>% 
   ggplot() +
   geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
   #geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
   #geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
   labs(title = "COVID-19 Rolling 14-day R-number, Missoula County",
        color = "") +
   ylab("R-number") +
   xlab("") +
   geom_hline(yintercept = 1, color = "red", size = 1.2) +
   scale_x_date(date_breaks = "3 days", date_labels = "%d-%b") +
   scale_y_continuous(breaks = seq(0, 5, 0.1), labels = seq(0, 5, 0.1)) +
   theme_minimal() +
   theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = c("black")) 
county_r_plot

#ggsave("C:/R/covid19/missoula_r_plot.png", width = 10, height = 6)
```

\pagebreak  

```{r, fig.width = 11, fig.height = 5}
# Epi curve - date of onset
plot_data <- covid_data %>% 
   filter(symptom_onset_date_new > "2020-03-01") 

total_cases <- sum(covid_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_onset <- plot_data %>% 
   filter(!is.na(symptom_onset_date_new)) %>% 
   ggplot() +
     geom_rect(aes(xmin = Sys.Date() - 14, xmax = Sys.Date(), ymin=0, ymax=Inf),
               fill = "gray80", alpha = 0.05) +
     geom_col(aes(symptom_onset_date_new, case, fill = symptom_onset_date_indicator)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-03-16")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-03-16"), label = "Schools close", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-03-28")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-03-28"), label = "Shelter in place order", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-04-26")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-04-26"), label = "Phase 1 reopening", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-06-01")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-06-01"), label = "Phase 2 reopening", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-07-09")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-07-09"), label = "Mask Mandate", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-09-07")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-09-07"), label = "Labor Day", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-05-25")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-05-25"), label = "Memorial Day", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-07-04")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-07-04"), label = "July 4th", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_vline(xintercept = as.numeric(as.Date("2020-08-19")), color = "black", 
              size = 1, linetype = "dashed") +
     geom_text(aes(x = as.Date("2020-08-19"), label = "UM semester start", vjust = -0.5,
                 y = 100), colour = "black", angle = 90, text = element_text(size=14)) +
     geom_label(aes(x = Sys.Date()-15, y = 120, 
                    label = "Cases from the shaded \n dates may not yet be \n reflected in the graph."),
                fill = NA) +
     labs(title = "COVID-19 Cases in Missoula County by Date, 2020",
          subtitle = paste0("Total cases = ", total_cases),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(breaks = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "6 days"),
                  labels = seq.Date(from = as.Date("2020-03-06"), 
                                    to = as.Date(Sys.Date()), 
                                    by = "6 days"),
                  date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.position = "top",
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank())  +
     scale_fill_manual(values = cbPalette) 

epi_curve_onset

#ggsave("epi_curve_onset.jpg", width = 12, height = 5.5)
```


