---
title: "MCCHD Covid-19 data cleaning, Rt, Doubling Time"
author: "Ethan Walker"
date: "23 August 2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(incidence)
library(EpiEstim)
```


```{r}
# Load data and format columns

# Update input path to file location on your computer
input_path <- c("C:/Users/ethan.walker/Box/Missoula_COVID19EpiProfile_Working/")


covid_data_initial <- 
   read_xlsx(paste0(input_path, "COVID Data 8.19.2021.xlsx"), sheet = 1,
             range = "A2:N20000", na = c(" ", ""),
                        col_names = c("case_id", "case_status", "health_worker", 
                                      "cong_living", "cong_living_where", "age", 
                                      "sex", "zip", "test_date", "um_student", "race", 
                                      "ethnicity", "ever_hosp", 
                                      "epi_linked"),
                        col_types = c("text", "text", "text", 
                                      "text", "text", "text",
                                      "text", "text", "date", "text", "text",
                                      "text", "text", 
                                      "text"))
```


```{r}
# Clean data

covid_clean <- covid_data_initial %>% 
   #select(case_id, case_status, age, sex, test_date) %>% 
   filter(!is.na(case_id)) %>% 
   mutate(age = as.numeric(age),
          age_group = cut(age, breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 130),
                          labels = c("0 to 9, 0.101", "10 to 19, 0.117", "20 to 29, 0.191", 
                                     "30 to 39, 0.143", "40 to 49, 0.115", "50 to 59, 0.112", 
                                     "60 to 69, 0.118", "70 to 79, 0.072", "80+, 0.032"), right = FALSE),
          age_group2 = cut(age, breaks = c(0, 18, 65, 130),
                          labels = c("<18", "18 to 64", "65+"), right = FALSE),
          age_group3 = cut(age, breaks = c(0, 5, 14, 18, 25, 30, 40, 50, 60, 70, 80, 130),
                          labels = c("0 to 4, 0.0503", "5 to 13, 0.095", "14 to 17, 0.0405", 
                                     "18 to 24, 0.137", "25 to 29, 0.086", 
                                     "30 to 39, 0.143", "40 to 49, 0.115", "50 to 59, 0.112", 
                                     "60 to 69, 0.118", "70 to 79, 0.072", "80+, 0.032"), right = FALSE)) %>% 
   separate(age_group, c("age_group", "age_group_percent"), sep = ", ") %>% 
   separate(age_group3, c("age_group3", "age_group3_percent"), sep = ", ") %>% 
   mutate_if(is.character, tolower) %>% 
   mutate_if(is.factor, tolower) %>% 
   replace_with_na_all(condition = ~.x %in% c("n/a", "na", "unknown", "unkown")) %>% 
   separate(test_date, into = c("test_date", "time"), sep = " ") %>% 
   mutate(age_group_percent = as.numeric(age_group_percent),
          age_group3_percent = as.numeric(age_group3_percent),
          county_pop = as.numeric(119600),
          case = 1,
          sex = as.factor(sex),
          case_status = as.factor(case_status),
          health_worker = as.factor(health_worker),
          cong_living = as.factor(cong_living),
          race = as.factor(race),
          ethnicity = as.factor(ethnicity),
          ever_hosp = sub("\\s", "", ever_hosp),
          ever_hosp = if_else(ever_hosp != "y" & ever_hosp != "yes", "no", ever_hosp),
          ever_hosp = if_else(is.na(ever_hosp), "no", ever_hosp),
          ever_hosp = as.factor(ever_hosp),
          hospitalizations = fct_collapse(ever_hosp,
                                          "no" = c("n", NA),
                                          "yes" = c("y", "yes")),
          epi_linked = as.factor(epi_linked),
          age_group = as.factor(age_group),
          age_group2 = as.factor(age_group2),
          test_date = ymd(test_date),
          age_group3 = factor(age_group3,
                              levels = c("0 to 4", "5 to 13", "14 to 17", 
                                     "18 to 24", "25 to 29", 
                                     "30 to 39", "40 to 49", "50 to 59", 
                                     "60 to 69", "70 to 79", "80+"),
                              labels = c("0 to 4", "5 to 13", "14 to 17", 
                                     "18 to 24", "25 to 29", 
                                     "30 to 39", "40 to 49", "50 to 59", 
                                     "60 to 69", "70 to 79", "80+"))) 
   

summary(covid_clean)
```


```{r}
# Check doubling time

inc_data <- covid_clean %>% 
   rename(dates = test_date) %>% 
   filter(!is.na(dates)) %>% 
   filter(dates > Sys.Date() - 42 & dates < Sys.Date() - 14) %>% 
   arrange(dates) %>% 
   select(dates, case) %>% 
   group_by(dates) %>% 
   mutate(total_cases = sum(case, na.rm = TRUE)) %>% 
   arrange(dates) %>% 
   ungroup()

inc_data2 <- incidence(inc_data$dates)

plot(inc_data2)

inc_fit <- fit(inc_data2)
inc_fit
inc_fit$info$doubling # doubling time to report to D'Shane

#plot(inc_fit)

#find_peak(inc_data2)
```


```{r}
## Missoula county R results using county data

case_data <- covid_clean %>% 
   rename(dates = test_date) %>% 
   filter(!is.na(dates)) %>% 
   filter(dates > "2020-12-31" & dates < Sys.Date() - 13) %>% 
   arrange(dates) %>% 
   select(dates, case) %>% 
   arrange(dates) %>% 
   ungroup() 

latest_date <- format(Sys.Date() - 14, "%Y-%m-%d")

incidence_data <- incidence(case_data$dates, last_date = latest_date)

# Set dates for 14-day rolling averages
county_n <- as.data.frame(incidence_data$dates)
time_var <- nrow(county_n)
time_start <- seq(2, time_var-13)
time_end <- time_start + 13


# Serial Interval derived from State of Montana paired case data
serial_interval_mean <- 4.42
serial_interval_sd <- 3.51

r_results <- estimate_R(incidence_data, method="parametric_si", 
                           config = make_config(list(mean_si = serial_interval_mean, 
                                                     std_si = serial_interval_sd,
                                                     t_start =  time_start,
                                                     t_end = time_end)))

# Format and save analysis results
colomns <- c(1:4, 8)
county_r <- (r_results$R[,colomns]) %>% 
   mutate(region = "Missoula County") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

county_dates <- as.data.frame(r_results$dates)
county_i <- as.data.frame(r_results$I)
county_cil <- as.data.frame(r_results$R$`Quantile.0.025(R)`)
county_cih <- as.data.frame(r_results$R$`Quantile.0.975(R)`)
county_dates_new <- cbind(county_dates, county_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
county_dates_new <- county_dates_new[-(1:14), 1:2]
county_dates_new <- cbind(county_dates_new, county_cil, county_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
county_r <- cbind(county_r, county_dates_new) # Report mean_r from latest date

# Or estimate Rt from plot below


county_r_plot <- county_r %>% 
   filter(dates > "2020-12-31") %>% 
   ggplot() +
   geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
   #geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
   #geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
   labs(title = "COVID-19 Rolling 14-day R-number, Missoula County",
        color = "") +
   ylab("R-number") +
   xlab("") +
   geom_hline(yintercept = 1, color = "red", size = 1.2) +
   scale_x_date(date_breaks = "5 days", date_labels = "%d-%b") +
   scale_y_continuous(breaks = seq(0, 5, 0.1), labels = seq(0, 5, 0.1)) +
   theme_minimal() +
   theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 18, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 16, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 16, colour = "black"),
         legend.text = element_text(size = 16, colour = "black"),
         axis.title.y = element_text(size = 16, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 16, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = c("black")) 
county_r_plot

#ggsave("C:/R/covid19/missoula_r_plot.png", width = 12, height = 6)
```
