---
title: "State of Montana Covid-19 data analysis practice/testing"
author: "Ethan Walker"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 8, fig.height = 6)
```

```{r, message=FALSE}
library(tidyverse)
#library(plyr)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(eeptools)
library(knitr)
library(incidence)
library(EpiEstim)
library(earlyR)
library(projections)
library(distcrete)
library(epitrix)
library(jsonlite)
library(httr)
library(rlist)
library(Rsftp)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
```


```{r}
query_url <- "https://services.arcgis.com/qnjIrwR8z5Izc0ij/ArcGIS/rest/services/COVID_Cases_Production_View/FeatureServer/2/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=OBJECTID%2C+Case_No%2C+Date_Reported_to_CDEpi%2C+County%2C+Age_Group%2C+Sex%2C+Hospitalization%2C+Outcome%2C+MT_case&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token="

initial_pull <- GET(query_url)

text_data <- content(initial_pull, as = "text")

parsed_data <- content(initial_pull, as = "parsed")

json_data <- fromJSON(text_data)

state_data <- as.data.frame(json_data$features$attributes) 

reg1 <- as.data.frame(c("Carter", "Custer", "Daniels", "Dawson", "Fallon", "Garfield", "McCone",
          "Phillips", "Powder River", "Prairie", "Richland", "Roosevelt", "Rosebud",
          "Sheridan", "Treasure", "Valley", "Wibaux")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 1)

reg2 <- as.data.frame(c("Blaine", "Cascade", "Chouteau", "Glacier", "Hill", "Liberty", "Pondera",
          "Teton", "Toole")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 2)

reg3 <- as.data.frame(c("Big Horn", "Carbon", "Fergus", "Golden Valley", "Judith Basin",
          "Musselshell", "Petroleum", "Stillwater", "Sweet Grass", "Wheatland",
          "Yellowstone")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 3)

reg4 <- as.data.frame(c("Beaverhead", "Broadwater", "Deer Lodge", "Gallatin", "Granite", "Jefferson",
          "Lewis and Clark", "Madison", "Meagher", "Park", "Powell", "Silver Bow")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 4)

reg5 <- as.data.frame(c("Flathead", "Lake", "Lincoln", "Mineral", "Missoula", 
          "Ravalli", "Sanders")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 5)

counties_regions <- rbind(reg1, reg2, reg3, reg4, reg5)

state_data_clean <- state_data %>% 
   rename_all(tolower) %>% 
   mutate(date_reported_to_cdepi = date_reported_to_cdepi/1000,
          dates = as.POSIXct(date_reported_to_cdepi, origin = "1970-01-01")) %>% 
   separate(dates, c("dates", "trash"), sep = " ") %>% 
   mutate(dates = ymd(dates)) %>% 
   select(case_no, dates, county:mt_case) %>% 
   left_join(counties_regions, by = "county") %>% 
   mutate(case = 1) %>% 
   mutate(age_group2 = if_else(age_group == "80-89" | age_group == "90-99",
                               "80+", age_group),
          age_group_new = factor(age_group2, 
                              levels = c("0-9", "10-19", "20-29", 
                                         "30-39", "40-49", "50-59", 
                                         "60-69", "70-79", "80+"),
                              labels = c("0 to 9, 0.12", "10 to 19, 0.13", "20 to 29, 0.13", 
                                         "30 to 39, 0.13", "40 to 49, 0.11", "50 to 59, 0.13", 
                                         "60 to 69, 0.14", "70 to 79, 0.08", "80+, 0.04"))) %>% 
   separate(age_group_new, c("age_group_new", "age_group_new_percent"), sep = ",") %>% 
   mutate(age_group_new_percent = as.numeric(age_group_new_percent),
          state_pop = as.numeric(1062000)) %>% 
   select(-age_group2) %>% 
   mutate(hospitalization = factor(hospitalization,
                                   levels = c("Y", "N", "P", "U"),
                                   labels = c("Hosp: Yes", "Hosp: No", 
                                              "Hosp: Past", "Hosp: Unknown"))) %>% 
   select(-case_no) %>% 
   rownames_to_column(var = "case_no") 

output_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

write_rds(state_data_clean, paste0(output_path, "Output/state_data_clean.rds"))
write_csv(state_data_clean, paste0(output_path, "Output/state_data_clean.csv"), na = " ")
  
```

```{r}
county_function <- function(county_name, data = state_data_clean){

county_data <- data %>% 
   filter(county == county_name) %>% 
   select(-case_no) %>% 
   rownames_to_column(var = "case_no")

county_incidence <- incidence(county_data$dates, 
                              first_date = "2020-03-13", 
                              last_date = Sys.Date(),
                              standard = FALSE)
county_dates <- as.data.frame(county_incidence$dates) %>% 
   rename_at(1, ~"dates")
county_cases <- county_incidence$counts

county_data_new <<- county_dates %>% 
   left_join(county_data, by = "dates") %>% 
   mutate(case_new = case) %>% 
   group_by(dates) %>% 
   mutate(hospitalization = as.character(hospitalization)) %>% 
   pivot_wider(names_from = "hospitalization", values_from = "case") %>% 
   select(-"NA") %>% 
   group_by(dates) %>% 
   pivot_wider(names_from = "outcome", values_from = "case_new") %>% 
   select(-"NA") %>% 
   group_by(dates) %>% 
   mutate_at(vars(one_of("Hosp: No")), sum, na.rm = TRUE) %>% 
   mutate_at(vars(one_of("Hosp: Yes")), sum, na.rm = TRUE) %>% 
   mutate_at(vars(one_of("Hosp: Unkown")), sum, na.rm = TRUE) %>% 
   mutate_at(vars(one_of("Hosp: Past")), sum, na.rm = TRUE) %>% 
   mutate_at(vars(one_of("Active")), sum, na.rm = TRUE) %>% 
   mutate_at(vars(one_of("Deceased")), sum, na.rm = TRUE) %>% 
   mutate_at(vars(one_of("Recovered")), sum, na.rm = TRUE) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   fill(county, .direction = c("downup")) %>% 
   fill(region, .direction = c("downup")) %>% 
   select(-case_no, -age_group, -sex, -mt_case, -age_group_new,
          -age_group_new_percent, -state_pop)



}

missoula_county <- county_function("Missoula")
gallatin_county <- county_function("Gallatin")
yellowstone_county <- county_function("Yellowstone")
richland_county <- county_function("Richland")
roosevelt_county <- county_function("Roosevelt")
cascade_county <- county_function("Cascade")
glacier_county <- county_function("Glacier")
hill_county <- county_function("Hill")
liberty_county <- county_function("Liberty")
pondera_county <- county_function("Pondera")
toole_county <- county_function("Toole")
bighorn_county <- county_function("Big Horn")
carbon_county <- county_function("Carbon")
fergus_county <- county_function("Fergus")
gvalley_county <- county_function("Golden Valley")
musselshell_county <- county_function("Musselshell")
stillwater_county <- county_function("Stillwater")
wheatland_county <- county_function("Wheatland")
beaverhead_county <- county_function("Beaverhead")
broadwater_county <- county_function("Broadwater")
deerlodge_county <- county_function("Deer Lodge")
jefferson_county <- county_function("Jefferson")
lewisandclark_county <- county_function("Lewis and Clark")
madison_county <- county_function("Madison")
meagher_county <- county_function("Meagher")
park_county <- county_function("Park")
silverbow_county <- county_function("Silver Bow")
flathead_county <- county_function("Flathead")
lake_county <- county_function("Lake")
lincoln_county <- county_function("Lincoln")
ravalli_county <- county_function("Ravalli")
rosebud_county <- county_function("Rosebud")
custer_county <- county_function("Custer")
dawson_county <- county_function("Dawson")
valley_county <- county_function("Valley")
treasure_county <- county_function("Treasure")
granite_county <- county_function("Granite")
fallon_county <- county_function("Fallon")
garield_county <- county_function("Garfield")
sheridan_county <- county_function("Sheridan")
teton_county <- county_function("Teton")
daniels_county <- county_function("Daniels")
mccone_county <- county_function("McCone")
priver_county <- county_function("Powder River")
wibaux_county <- county_function("Wibaux")
blaine_county <- county_function("Blaine")
chouteau_county <- county_function("Chouteau")
jbasin_county <- county_function("Judith Basin")
sweetgrass_county <- county_function("Sweet Grass")
sanders_county <- county_function("Sanders")




county_data_combined <- plyr::rbind.fill(missoula_county, gallatin_county,
                                         yellowstone_county, richland_county,
                                         roosevelt_county, cascade_county,
                                         glacier_county, hill_county,
                                         liberty_county, pondera_county,
                                         toole_county, bighorn_county,
                                         carbon_county, fergus_county,
                                         gvalley_county, musselshell_county,
                                         stillwater_county, wheatland_county,
                                         beaverhead_county, broadwater_county,
                                         deerlodge_county, jefferson_county,
                                         lewisandclark_county, madison_county,
                                         meagher_county, park_county,
                                         silverbow_county, flathead_county,
                                         lake_county, lincoln_county,
                                         ravalli_county, rosebud_county,
                                         custer_county, dawson_county,
                                         valley_county, treasure_county,
                                         granite_county, fallon_county,
                                         garield_county, sheridan_county,
                                         teton_county, daniels_county,
                                         mccone_county, priver_county, 
                                         wibaux_county, blaine_county,
                                         chouteau_county, jbasin_county,
                                         sweetgrass_county, sanders_county) 

output_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

write_csv(county_data_combined, paste0(output_path, "Output/county_data_combined.csv"))

carter_county <- county_function("Carter")
phillips_county <- county_function("Phillips")
prairie_county <- county_function("Prairie")
petroleum_county <- county_function("Petroleum")
powell_county <- county_function("Powell")
mineral_county <- county_function("Mineral")
```


```{r}
state_hosp <- state_data_clean %>% 
   filter(mt_case != "N" & mt_case != "X") %>% 
   group_by(age_group_new) %>% 
   mutate(age_group_cases = sum(case)) %>% 
   mutate(hosp = if_else(hospitalization == "Hosp: Yes" | hospitalization == "Hosp: Past", 1, 0),
          hosp_yes = sum(hosp, na.rm = TRUE),
          hosp_no = age_group_cases - hosp_yes,
          hosp_percent = round(hosp_yes/age_group_cases*100, digits = 2)) %>% 
   ungroup() %>% 
   distinct(age_group_new, .keep_all = TRUE) %>% 
   select(age_group_new, age_group_cases, hosp_yes, hosp_no, hosp_percent) %>% 
   rename(age_group = age_group_new) %>% 
   arrange(age_group)
#state_hosp

output_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

write_csv(state_hosp, paste0(output_path, "Output/state_hosp.csv"))
```

# test data
```{r}
query_url <- "https://services.arcgis.com/qnjIrwR8z5Izc0ij/ArcGIS/rest/services/COVID_Cases_Production_View/FeatureServer/1/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=OBJECTID%2C+Total_Tests_Completed%2C+New_Tests_Completed%2C+Test_Date%2C+ScriptRunDate&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token="

initial_pull <- GET(query_url)

text_data <- content(initial_pull, as = "text")

parsed_data <- content(initial_pull, as = "parsed")

json_data <- fromJSON(text_data)

state_test_data <- as.data.frame(json_data$features$attributes) 

state_test_data_clean <- state_test_data %>% 
   rename_all(tolower) %>% 
   mutate(dates = test_date/1000,
          dates = as.POSIXct(dates, origin = "1970-01-01")) %>% 
   separate(dates, c("dates", "trash"), sep = " ") %>% 
   mutate(dates = ymd(dates)) %>% 
   select(dates, total_tests_completed, new_tests_completed) %>% 
   arrange(dates, desc(total_tests_completed)) %>% 
   distinct(dates, .keep_all = TRUE)
   

   

output_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

write_rds(state_test_data_clean, paste0(output_path, "Output/state_test_data_clean.rds"))
write_csv(state_test_data_clean, paste0(output_path, "Output/state_test_data_clean.csv"), na = " ")
  
```
 
 
# combine daily case and test data
```{r}
output_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")
state_test_data_clean <- read_rds(paste0(output_path, "Output/state_test_data_clean.rds"))
state_case_data_clean <- read_rds(paste0(output_path, "Output/state_data_clean.rds"))


hosp_data_daily <- state_case_data_clean %>% 
   filter(mt_case == "Y") %>% 
   select(dates, hospitalization, case) %>% 
   mutate(hospitalization = factor(hospitalization,
                                      labels = c("hosp_active",
                                                 "hosp_no",
                                                 "hosp_past",
                                                 "hosp_unknown"))) %>% 
   group_by(dates, hospitalization) %>% 
   mutate(sum_hosp = sum(case)) %>% 
   group_by(dates) %>% 
   select(-case) %>% 
   distinct(dates, hospitalization, .keep_all = TRUE) %>% 
   pivot_wider(names_from = "hospitalization", values_from = "sum_hosp") %>% 
   mutate(hosp_active = if_else(is.na(hosp_active), 0, hosp_active),
          hosp_no = if_else(is.na(hosp_no), 0, hosp_no),
          hosp_past = if_else(is.na(hosp_past), 0, hosp_past),
          hosp_unknown = if_else(is.na(hosp_unknown), 0, hosp_unknown)) %>% 
   group_by(dates) %>% 
   mutate(daily_hosp = hosp_active + hosp_past) %>% 
   ungroup() %>% 
   mutate(total_hosp = cumsum(daily_hosp)) %>% 
   select(dates, daily_hosp, total_hosp)


outcome_data_daily <- state_case_data_clean %>% 
   filter(mt_case == "Y") %>% 
   select(dates, outcome, case) %>% 
   mutate(outcome = factor(outcome,
                           labels = c("active",
                           "deceased",
                           "recovered"))) %>% 
   group_by(dates, outcome) %>% 
   mutate(total_outcome = sum(case)) %>% 
   group_by(dates) %>% 
   select(-case) %>% 
   distinct(dates, outcome, .keep_all = TRUE) %>% 
   pivot_wider(names_from = "outcome", values_from = "total_outcome") %>% 
   mutate(active = if_else(is.na(active), 0, active),
          deceased = if_else(is.na(deceased), 0, deceased),
          recovered = if_else(is.na(recovered), 0, recovered)) %>% 
   group_by(dates) %>% 
   mutate(daily_deceased = deceased,
          daily_active = active,
          daily_recovered = recovered) %>% 
   ungroup() %>% 
   mutate(total_deceased = cumsum(daily_deceased),
          total_active = cumsum(daily_active),
          total_recovered = cumsum(daily_recovered)) %>% 
   select(dates, daily_deceased, total_deceased, daily_active,
          total_active, daily_recovered, total_recovered)


case_data_daily <- state_case_data_clean %>% 
   filter(mt_case == "Y") %>% 
   select(dates, case) %>% 
   group_by(dates) %>% 
   mutate(daily_cases = sum(case)) %>% 
   ungroup() %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   mutate(total_cases = cumsum(daily_cases)) %>% 
   select(-case)


case_hosp_test_outcome <- case_data_daily %>% 
   left_join(hosp_data_daily, by = "dates") %>% 
   left_join(outcome_data_daily, by = "dates") %>% 
   full_join(state_test_data_clean, by = "dates") %>% 
   arrange(dates) %>% 
   mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>% 
   mutate(total_cases = cumsum(daily_cases),
          total_hosp = cumsum(daily_hosp),
          total_deceased = cumsum(daily_deceased),
          total_active = cumsum(daily_active),
          total_recovered = cumsum(daily_recovered),
          total_tests_completed = if_else(total_tests_completed == 0, 
                                          lag(total_tests_completed), total_tests_completed),
          total_tests_completed = if_else(total_tests_completed == 0, 
                                          lag(total_tests_completed), total_tests_completed),
          total_tests_completed = if_else(is.na(total_tests_completed), 
                                          0, total_tests_completed)) %>% 
   rename(total_tests = total_tests_completed,
          daily_tests = new_tests_completed)

write_csv(case_hosp_test_outcome, paste0(output_path, "Output/mt_daily_case_test_data.csv"), na = " ")
```

 
```{r}
state_data_wide <- state_data_clean %>% 
   mutate(age_group = factor(age_group,
                             labels = c("<10 yrs", "10 to 19 yrs",
                                        "20 to 29 yrs", "30 to 39 yrs",
                                        "40 to 49 yrs", "50 to 59 yrs",
                                        "60 to 69 yrs", "70 to 79 yrs",
                                        "80 to 89 yrs", "90 to 99 yrs")),
          sex = factor(sex, labels = c("Female", "Male")),
          hospitalization = factor(hospitalization,
                                   labels = c("Hosp: No", "Hosp: Past",
                                              "Hosp: Unknown", "Hosp: Yes"))) %>% 
   mutate(case = 1) %>% 
   pivot_wider(names_from = "age_group", values_from = "case") %>% 
   mutate(case = 1) %>% 
   pivot_wider(names_from = "sex", values_from = "case") %>% 
   mutate(case = 1) %>% 
   pivot_wider(names_from = "hospitalization", values_from = "case") %>% 
   mutate(case = 1) %>% 
   pivot_wider(names_from = "county", values_from = "case")

state_wide_date <- state_data_wide %>% 
   mutate(region = "state") %>% 
   group_by(dates) %>% 
   mutate_at(c(9:55), sum, na.rm = TRUE) %>% 
   mutate(case = 1,
          daily_cases = sum(case)) %>% 
   arrange(dates) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   mutate(cumulative_cases = cumsum(daily_cases)) %>% 
   select(region, dates, daily_cases, cumulative_cases, `70 to 79 yrs`:Pondera)

reg1_wide_date <- state_data_wide %>% 
   filter(region == 1) %>% 
   group_by(dates) %>% 
   mutate_at(c(9:55), sum, na.rm = TRUE) %>% 
   mutate(case = 1,
          daily_cases = sum(case)) %>% 
   arrange(dates) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   mutate(cumulative_cases = cumsum(daily_cases)) %>% 
   select(region, dates, daily_cases, cumulative_cases, `70 to 79 yrs`:Pondera)

reg2_wide_date <- state_data_wide %>% 
   filter(region == 2) %>% 
   group_by(dates) %>% 
   mutate_at(c(9:55), sum, na.rm = TRUE) %>% 
   mutate(case = 1,
          daily_cases = sum(case)) %>% 
   arrange(dates) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   mutate(cumulative_cases = cumsum(daily_cases)) %>% 
   select(region, dates, daily_cases, cumulative_cases, `70 to 79 yrs`:Pondera)

reg3_wide_date <- state_data_wide %>% 
   filter(region == 3) %>% 
   group_by(dates) %>% 
   mutate_at(c(9:55), sum, na.rm = TRUE) %>% 
   mutate(case = 1,
          daily_cases = sum(case)) %>% 
   arrange(dates) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   mutate(cumulative_cases = cumsum(daily_cases)) %>% 
   select(region, dates, daily_cases, cumulative_cases, `70 to 79 yrs`:Pondera)

reg4_wide_date <- state_data_wide %>% 
   filter(region == 4) %>% 
   group_by(dates) %>% 
   mutate_at(c(9:55), sum, na.rm = TRUE) %>% 
   mutate(case = 1,
          daily_cases = sum(case)) %>% 
   arrange(dates) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   mutate(cumulative_cases = cumsum(daily_cases)) %>% 
   select(region, dates, daily_cases, cumulative_cases, `70 to 79 yrs`:Pondera)

reg5_wide_date <- state_data_wide %>% 
   filter(region == 5) %>% 
   group_by(dates) %>% 
   mutate_at(c(9:55), sum, na.rm = TRUE) %>% 
   mutate(case = 1,
          daily_cases = sum(case)) %>% 
   arrange(dates) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   ungroup() %>% 
   mutate(cumulative_cases = cumsum(daily_cases)) %>% 
   select(region, dates, daily_cases, cumulative_cases, `70 to 79 yrs`:Pondera)

all_data_wide <- rbind(state_wide_date, reg1_wide_date, reg2_wide_date,
                       reg3_wide_date, reg4_wide_date, reg5_wide_date)

state_data_incidence <- state_data %>% 
   rename_all(tolower) %>% 
   mutate(date_reported_to_cdepi = date_reported_to_cdepi/1000,
          dates = as.POSIXct(date_reported_to_cdepi, origin = "1970-01-01")) %>% 
   separate(dates, c("dates", "trash"), sep = " ") %>% 
   mutate(dates = ymd(dates)) %>% 
   select(case_no, dates, county:mt_case) %>% 
   group_by(dates) %>% 
   mutate(I = n()) %>% 
   ungroup() %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   select(dates, I)
```


```{r}
serial_interval_mean <- 4
serial_interval_sd <- 4.75


## State results
state_incidence <- incidence(state_data_clean$dates)

state_results <- estimate_R(state_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

#state_plot <- estimate_R_plots(state_results, what = "R")

colomns <- c(1:4, 8)
state_r <- (state_results$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(state_results$dates)
state_i <- as.data.frame(state_results$I)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-(1:7), 1:2]
state_r_clean <- cbind(state_r, state_dates_new) 


total_cases <- sum(state_data_clean$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_10 <- format(Sys.Date() - 10, "%d %b %Y")


state_r_plot <- state_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     labs(title = "COVID-19 Rolling 7-day R-values, State of Montana, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     scale_y_continuous(breaks = seq(0, 5, 0.25), labels = seq(0, 5, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
#state_r_plot

state_inc_plot <- state_data_clean %>% 
   ggplot() +
     geom_col(aes(dates, case), 
              fill = "steelblue") +
     labs(title = paste0("COVID-19 Cases in State of Montana, 2020", 
                         " (Total cases = ", total_cases, ")"),
          subtitle = paste0("Data current as of ", date_today)) +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(date_breaks = "2 day", date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) 
#state_inc_plot

ggsave("state_r_plot.png")
ggsave("state_inc_plot.png")



## Reg1 results
reg1_data <- state_data_clean %>% 
   filter(region == 1)

reg1_incidence <- incidence(reg1_data$dates)

reg1_results <- estimate_R(reg1_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

#reg1_plot <- estimate_R_plots(reg1_results, what = "R")


colomns <- c(1:4, 8)
reg1_r <- (reg1_results$R[,colomns]) %>% 
   mutate(region = "1") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

reg1_dates <- as.data.frame(reg1_results$dates)
reg1_i <- as.data.frame(reg1_results$I)
reg1_dates_new <- cbind(reg1_dates, reg1_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
reg1_dates_new <- reg1_dates_new[-(1:7), 1:2]
reg1_r_clean <- cbind(reg1_r, reg1_dates_new)

reg1_data_clean <- state_data_clean %>% 
   filter(region == 1)
total_cases <- sum(reg1_data_clean$case)


reg1_r_plot <- reg1_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     labs(title = "COVID-19 Rolling 7-day R-values, Montana Region 1, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     scale_y_continuous(breaks = seq(0, 20, 2), labels = seq(0, 20, 2)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
#reg1_r_plot

reg1_inc_plot <- reg1_data_clean %>% 
   ggplot() +
     geom_col(aes(dates, case), 
              fill = "steelblue") +
     labs(title = paste0("COVID-19 Cases in Montana Region 1, 2020", 
                         " (Total cases = ", total_cases, ")"),
          subtitle = paste0("Data current as of ", date_today)) +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(date_breaks = "2 day", date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) 
#reg1_inc_plot

ggsave("reg1_r_plot.png")
ggsave("reg1_inc_plot.png")



## Reg2 results
reg2_data <- state_data_clean %>% 
   filter(region == 2)

reg2_incidence <- incidence(reg2_data$dates)

reg2_results <- estimate_R(reg2_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

#reg2_plot <- estimate_R_plots(reg2_results, what = "R")


colomns <- c(1:4, 8)
reg2_r <- (reg2_results$R[,colomns]) %>% 
   mutate(region = "2") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

reg2_dates <- as.data.frame(reg2_results$dates)
reg2_i <- as.data.frame(reg2_results$I)
reg2_dates_new <- cbind(reg2_dates, reg2_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
reg2_dates_new <- reg2_dates_new[-(1:7), 1:2]
reg2_r_clean <- cbind(reg2_r, reg2_dates_new)


reg2_data_clean <- state_data_clean %>% 
   filter(region == 2)
total_cases <- sum(reg2_data_clean$case)


reg2_r_plot <- reg2_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     labs(title = "COVID-19 Rolling 7-day R-values, Montana Region 2, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     scale_y_continuous(breaks = seq(0, 10, 0.25), labels = seq(0, 10, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
#reg2_r_plot

reg2_inc_plot <- reg2_data_clean %>% 
   ggplot() +
     geom_col(aes(dates, case), 
              fill = "steelblue") +
     labs(title = paste0("COVID-19 Cases in Montana Region 2, 2020", 
                         " (Total cases = ", total_cases, ")"),
          subtitle = paste0("Data current as of ", date_today)) +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(date_breaks = "2 day", date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) 
#reg2_inc_plot

ggsave("reg2_r_plot.png")
ggsave("reg2_inc_plot.png")


## Reg3 results
reg3_data <- state_data_clean %>% 
   filter(region == 3)

reg3_incidence <- incidence(reg3_data$dates)

reg3_results <- estimate_R(reg3_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

#reg3_plot <- estimate_R_plots(reg3_results, what = "R")

colomns <- c(1:4, 8)
reg3_r <- (reg3_results$R[,colomns]) %>% 
   mutate(region = "3") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

reg3_dates <- as.data.frame(reg3_results$dates)
reg3_i <- as.data.frame(reg3_results$I)
reg3_dates_new <- cbind(reg3_dates, reg3_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
reg3_dates_new <- reg3_dates_new[-(1:7), 1:2]
reg3_r_clean <- cbind(reg3_r, reg3_dates_new)


reg3_data_clean <- state_data_clean %>% 
   filter(region == 3)
total_cases <- sum(reg3_data_clean$case)


reg3_r_plot <- reg3_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     labs(title = "COVID-19 Rolling 7-day R-values, Montana Region 3, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     scale_y_continuous(breaks = seq(0, 10, 0.25), labels = seq(0, 10, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
#reg3_r_plot

reg3_inc_plot <- reg3_data_clean %>% 
   ggplot() +
     geom_col(aes(dates, case), 
              fill = "steelblue") +
     labs(title = paste0("COVID-19 Cases in Montana Region 3, 2020", 
                         " (Total cases = ", total_cases, ")"),
          subtitle = paste0("Data current as of ", date_today)) +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(date_breaks = "2 day", date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) 
#reg3_inc_plot

ggsave("reg3_r_plot.png")
ggsave("reg3_inc_plot.png")


## Reg4 results
reg4_data <- state_data_clean %>% 
   filter(region == 4)

reg4_incidence <- incidence(reg4_data$dates)

reg4_results <- estimate_R(reg4_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

#reg4_plot <- estimate_R_plots(reg4_results, what = "R")

colomns <- c(1:4, 8)
reg4_r <- (reg4_results$R[,colomns]) %>% 
   mutate(region = "4") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

reg4_dates <- as.data.frame(reg4_results$dates)
reg4_i <- as.data.frame(reg4_results$I)
reg4_dates_new <- cbind(reg4_dates, reg4_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
reg4_dates_new <- reg4_dates_new[-(1:7), 1:2]
reg4_r_clean <- cbind(reg4_r, reg4_dates_new)


reg4_data_clean <- state_data_clean %>% 
   filter(region == 4)
total_cases <- sum(reg4_data_clean$case)


reg4_r_plot <- reg4_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     labs(title = "COVID-19 Rolling 7-day R-values, Montana Region 4, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     scale_y_continuous(breaks = seq(0, 10, 0.25), labels = seq(0, 10, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
#reg4_r_plot

reg4_inc_plot <- reg4_data_clean %>% 
   ggplot() +
     geom_col(aes(dates, case), 
              fill = "steelblue") +
     labs(title = paste0("COVID-19 Cases in Montana Region 4, 2020", 
                         " (Total cases = ", total_cases, ")"),
          subtitle = paste0("Data current as of ", date_today)) +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(date_breaks = "2 day", date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) 
#reg4_inc_plot

ggsave("reg4_r_plot.png")
ggsave("reg4_inc_plot.png")


## Reg5 results
reg5_data <- state_data_clean %>% 
   filter(region == 5)

reg5_incidence <- incidence(reg5_data$dates)

reg5_results <- estimate_R(reg5_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

#reg5_plot <- estimate_R_plots(reg5_results, what = "R")

colomns <- c(1:4, 8)
reg5_r <- (reg5_results$R[,colomns]) %>% 
   mutate(region = "5") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

reg5_dates <- as.data.frame(reg5_results$dates)
reg5_i <- as.data.frame(reg5_results$I)
reg5_dates_new <- cbind(reg5_dates, reg5_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
reg5_dates_new <- reg5_dates_new[-(1:7), 1:2]
reg5_r_clean <- cbind(reg5_r, reg5_dates_new)


reg5_data_clean <- state_data_clean %>% 
   filter(region == 5)
total_cases <- sum(reg5_data_clean$case)


reg5_r_plot <- reg5_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     labs(title = "COVID-19 Rolling 7-day R-values, Montana Region 5, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     scale_y_continuous(breaks = seq(0, 10, 0.25), labels = seq(0, 10, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
#reg5_r_plot

reg5_inc_plot <- reg5_data_clean %>% 
   ggplot() +
     geom_col(aes(dates, case), 
              fill = "steelblue") +
     labs(title = paste0("COVID-19 Cases in Montana Region 5, 2020", 
                         " (Total cases = ", total_cases, ")"),
          subtitle = paste0("Data current as of ", date_today)) +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(date_breaks = "2 day", date_labels = "%d-%b") +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) 
#reg5_inc_plot

ggsave("reg5_r_plot.png")
ggsave("reg5_inc_plot.png")



# Bind files and save
all_regions_r <- rbind(state_r_clean, reg1_r_clean, reg2_r_clean, reg3_r_clean, 
                       reg4_r_clean, reg5_r_clean) %>% 
   left_join(all_data_wide, by = c("region", "dates"))

write_csv(all_regions_r, "all_regions_r.csv", na = " ")
```

```{r, eval=FALSE, include=FALSE}
# Send it to the sftp server
# host = 'elbastion.dbs.umt.edu'
# port = 22
# username = 'celftp'
# password  = 'celftp'
# remotepath = '/celFtpFiles/covid19/Rt/incoming/'

sftpUpload("elbastion.dbs.umt.edu", "celftp", "celftp",
           "/celFtpFiles/covid19/Rt/incoming/all_regions_r.csv",
           "C:/R/covid19/state_daily_results/all_regions_r.csv")
```

```{r}
# County-level data

query_url <- "https://services.arcgis.com/qnjIrwR8z5Izc0ij/arcgis/rest/services/COVID_Cases_Production_View/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=OBJECTID%2C+NAME%2C+Total%2C+F_0_9%2C+M_0_9%2C+T_0_9%2C+F_10_19%2C+M_10_19%2C+T_10_19%2C+F_20_29%2C+M_20_29%2C+T_20_29%2C+F_30_39%2C+M_30_39%2C+T_30_39%2C+F_40_49%2C+M_40_49%2C+T_40_49%2C+F_50_59%2C+M_50_59%2C+T_50_59%2C+F_60_69%2C+M_60_69%2C+T_60_69%2C+F_70_79%2C+M_70_79%2C+T_70_79%2C+F_80_89%2C+M_80_89%2C+T_80_89%2C+F_90_99%2C+M_90_99%2C+T_90_99%2C+F_100%2C+M_100%2C+T_100%2C+Notes%2C+NewCases%2C+TotalDeaths%2C+HospitalizationCount%2C+TotalRecovered%2C+TotalActive%2C+&returnGeometry=false&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pjson&token="

initial_pull <- GET(query_url)

text_data <- content(initial_pull, as = "text")

parsed_data <- content(initial_pull, as = "parsed")

json_data <- fromJSON(text_data)

county_data <- as.data.frame(json_data$features$attributes) 
```

```{r}
serial_interval_mean <- 4
serial_interval_sd <- 4.75

#serial_interval_mean <- 4
#serial_interval_sd <- 6

# When experimenting with different serial interval mean/sd, the mean has an impact,
# but SD perhaps has more of an impact. Lower SD makes R go up - more certainty.
# Higher mean also makes R go up.


# Check earlyR results against some of the earlier R values from EpiEstim
date_earlyR <- state_data_clean %>% 
   filter(dates < "2020-03-29") 

incidence_earlyR <- incidence(date_earlyR$dates)

results_earlyR <- get_R(incidence_earlyR, 
                   si_mean = serial_interval_mean,
                   si_sd = serial_interval_sd)

results_earlyR



## State results
date_today <- Sys.Date()
state_incidence <- incidence(state_data_clean$dates, last_date = date_today)

state_n <- as.data.frame(state_incidence$dates)

time_var <- nrow(state_n)
time_start <- seq(2, time_var-13)
time_end <- time_start + 13

state_results1wk <- estimate_R(state_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd)))

state_results2wk <- estimate_R(state_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd,
                                                         t_start =  time_start,
                                                         t_end = time_end)))
#estimate_R_plots(state_results2wk, what = "R")

# Rolling 1 week R
colomns <- c(1:4, 8)
state_r <- (state_results1wk$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(state_results1wk$dates)
state_i <- as.data.frame(state_results1wk$I)
state_cil <- as.data.frame(state_results1wk$R$`Quantile.0.025(R)`)
state_cih <- as.data.frame(state_results1wk$R$`Quantile.0.975(R)`)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-(1:7), 1:2]
state_dates_new <- cbind(state_dates_new, state_cil, state_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
state_r_clean <- cbind(state_r, state_dates_new) 


total_cases <- sum(state_data_clean$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_10 <- format(Sys.Date() - 10, "%d %b %Y")


state_r_plot <- state_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
     geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
     labs(title = "COVID-19 Rolling 7-day R-values, State of Montana, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     #scale_y_continuous(breaks = seq(0, 5, 0.25), labels = seq(0, 5, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
state_r_plot


ggsave("state_r_1wk.png")


# Rolling 2 week R
colomns <- c(1:4, 8)
state_r <- (state_results2wk$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(state_results2wk$dates)
state_i <- as.data.frame(state_results2wk$I)
state_cil <- as.data.frame(state_results2wk$R$`Quantile.0.025(R)`)
state_cih <- as.data.frame(state_results2wk$R$`Quantile.0.975(R)`)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-(1:14), 1:2]
state_dates_new <- cbind(state_dates_new, state_cil, state_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
state_r_clean <- cbind(state_r, state_dates_new) 


state_r_plot <- state_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
     geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
     labs(title = "COVID-19 Rolling 14-day R-values, State of Montana, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     #scale_y_continuous(breaks = seq(0, 5, 0.25), labels = seq(0, 5, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
state_r_plot


ggsave("state_r_2wk.png")



# Daily R
state_incidence <- incidence(state_data_clean$dates)

state_n <- as.data.frame(state_incidence$dates)

time_var <- nrow(state_n)
time_start <- seq(2, time_var-1)
time_end <- time_start + 1

state_results_daily <- estimate_R(state_incidence, method="parametric_si", 
                               config = make_config(list(mean_si = serial_interval_mean, 
                                                         std_si = serial_interval_sd,
                                                         t_start =  time_start,
                                                         t_end = time_end)))

colomns <- c(1:4, 8)
state_r <- (state_results_daily$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(state_results_daily$dates)
state_i <- as.data.frame(state_results_daily$I)
state_cil <- as.data.frame(state_results_daily$R$`Quantile.0.025(R)`)
state_cih <- as.data.frame(state_results_daily$R$`Quantile.0.975(R)`)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-2, 1:2]
state_dates_new <- cbind(state_dates_new, state_cil, state_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
state_r_clean <- cbind(state_r, state_dates_new) 


state_r_plot <- state_r_clean %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
     geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
     labs(title = "COVID-19 Daily R-values, State of Montana, 2020",
          subtitle = paste0("Data current as of ", date_today),
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     #scale_y_continuous(breaks = seq(0, 5, 0.25), labels = seq(0, 5, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
state_r_plot


ggsave("state_r_daily.png")
```


```{r}
# check sample size for 4 counties
counties_filter <- state_data_clean %>% 
   #filter(county == "Missoula") %>% 
   #filter(county == "Gallatin") %>%
   #filter(county == "Flathead") %>%
   filter(county == "Yellowstone")
```


Projecting future incidence based on existing incidence data and R-value
```{r}
# https://www.repidemicsconsortium.org/projections/

# save si parameters
serial_interval_mean <- 4
serial_interval_sd <- 4.75

# save state incidence data
date_today <- Sys.Date()
state_incidence <- incidence(state_data_clean$dates, last_date = date_today)

# pre-SIP data for calculations below
dates_pre_sip <- state_data_clean %>% 
   filter(dates < "2020-03-29") 

# post-phase 1 data for calculations below
dates_post_phase1 <- state_data_clean %>% 
   filter(dates > "2020-04-25")



# Use date range of interest from above for the following calculations/plots:
incidence_earlyR <- incidence(dates_post_phase1$dates)

results_earlyR <- get_R(incidence_earlyR, 
                   si_mean = serial_interval_mean,
                   si_sd = serial_interval_sd)

# save a distribution of possible R values
r_distribution <- sample_R(results_earlyR)

# print distribution of R values
hist(r_distribution, border = "grey", col = "navy",
     xlab = "Values of R",
     main = "Sample of likely R values")

# save SI distribution from get_R calculation
si <- results_earlyR$si

# run projection
set.seed(123)
state_projection <- project(incidence_earlyR, R = r_distribution, si = si, n_days = 30, n_sim = 1000)

# plot projected data
plot(state_projection)

# project and plot cumulative cases
projected_cumulate <- cumulate(state_projection)
plot(projected_cumulate)

# plot projections over incidence data
plot(incidence_earlyR) %>% 
   add_projections(state_projection, boxplots = FALSE) %>% 
   add_projections(projected_cumulate)

# save last plot
ggsave("state_projections_phase1.png")
```

# Estimate serial interval using MT data
```{r}
# Load and format MT SI data
file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

mt_si_data_1 <- read_csv(paste0(file_path, "Input/si_data.csv")) %>% 
   select(-Pair_No) %>% 
   rename(EL = EL_Infector_Lower,
          ER = ER_Infector_Upper,
          SL = SL_Infected_Lower,
          SR = SR_Infected_Upper) %>% 
   mutate_all(as.integer) %>% 
   mutate(type = 0) %>% 
   filter(SR > 0) %>% 
   filter(SL > 0)

mt_si_data_2 <- read_csv(paste0(file_path, "Input/si_data.csv")) %>% 
   select(-Pair_No) %>% 
   rename(EL = EL_Infector_Lower,
          ER = ER_Infector_Upper,
          SL = SL_Infected_Lower,
          SR = SR_Infected_Upper) %>% 
   mutate(SL2 = if_else(SL<1, SL + (1 - SL), SL),
          SR2 = if_else(SL<1, SR + (1 - SL), SR)) %>% 
   select(EL, ER, SL2, SR2) %>% 
   rename(SL = SL2,
          SR = SR2) %>% 
   mutate_all(as.integer)

# Load data with import/local incidence
mt_li_data <- read_csv(paste0(file_path, "Input/local_import_data.csv")) %>% 
   filter(!is.na(`Date Reported to CDEpi`)) %>% 
   mutate(local = if_else(Local_Import == 0, 1, 0),
          imported = Local_Import,
          date_reported = mdy(`Date Reported to CDEpi`),
          date_onset = mdy(`Symptom Onset Date`),
          date_onset_est = mdy(`Estimated onset date`),
          dates = if_else(is.na(date_onset), date_onset_est, date_onset),
          dates = if_else(is.na(dates), date_reported, dates)) %>% 
   group_by(dates) %>% 
   mutate(local = sum(local),
          imported = sum(imported)) %>% 
   select(dates, local, imported) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   arrange(dates)

mt_data <- mt_li_data %>% 
   mutate(I = local + imported) %>% 
   select(dates, I) 

mt_incidence_data <- incidence(mt_data$dates)

mt_li_sep_data <- as.data.frame(mt_incidence_data$dates) %>% 
   mutate(dates = ymd(mt_incidence_data$dates)) %>% 
   select(dates) %>% 
   left_join(mt_li_data, by = "dates") %>% 
   mutate(local = if_else(is.na(local), 0, local),
          imported = if_else(is.na(imported), 0, imported))

mt_li_combined_data <- as.data.frame(mt_incidence_data$dates) %>% 
   mutate(dates = ymd(mt_incidence_data$dates)) %>% 
   left_join(mt_data, by = "dates") %>% 
   mutate(I = if_else(is.na(I), 0, I)) %>% 
   select(dates, I)


state_n <- as.data.frame(mt_incidence_data$dates)

time_var <- nrow(state_n)
time_start <- seq(2, time_var-13)
time_end <- as.integer(time_start + 13)



MCMC_seed <- 1
overall_seed <- 2
mcmc_control <- make_mcmc_control(seed = MCMC_seed, burnin = 1000, thin = 10)
dist <- "G"  # fitting a Gamma distribution for the SI
si_config <- make_config(list(si_parametric_distr = dist, 
    mcmc_control = mcmc_control, seed = overall_seed, n1 = 500, n2 = 50,
    t_start = time_start, t_end = time_end))

r_li_sep <- estimate_R(mt_li_sep_data, method = "si_from_data", 
    si_data = mt_si_data_1, config = si_config)

r_li_combined <- estimate_R(mt_li_combined_data, method = "si_from_data", 
    si_data = mt_si_data, config = si_config)

# plot R estimates using total incidence and local/imported incidence
plot_li_sep <- estimate_R_plots(r_li_sep, what = "R")
plot_li_combined <- estimate_R_plots(r_li_combined, what = "R")
plot_li_sep
plot_li_combined

# calculate mean serial interval using SI data
mean_si <- r_li_sep$SI.Moments %>% 
   summarize(mean_si = mean(Mean), sd_si = mean(Std)) 


# save R estimates and prep for plotting - total incidence
colomns <- c(1:4, 8)
state_r <- (r_li_combined$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(r_li_combined$dates)
state_i <- as.data.frame(r_li_combined$I)
state_cil <- as.data.frame(r_li_combined$R$`Quantile.0.025(R)`)
state_cih <- as.data.frame(r_li_combined$R$`Quantile.0.975(R)`)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-(1:14), 1:2]
state_dates_new <- cbind(state_dates_new, state_cil, state_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
state_r_clean_combined <- cbind(state_r, state_dates_new) 


# save R estimates and prep for plotting - local/imported incidence
colomns <- c(1:4, 8)
state_r <- (r_li_sep$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(r_li_sep$dates)
state_i <- as.data.frame(r_li_sep$I)
state_cil <- as.data.frame(r_li_sep$R$`Quantile.0.025(R)`)
state_cih <- as.data.frame(r_li_sep$R$`Quantile.0.975(R)`)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-(1:14), 1:2]
state_dates_new <- cbind(state_dates_new, state_cil, state_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
state_r_clean_sep <- cbind(state_r, state_dates_new) 


state_r_plot <- state_r_clean_combined %>% 
   ggplot() +
     geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
     geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
     geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
     labs(title = "COVID-19 Rolling 14-day R-values, State of Montana, 2020",
          color = "") +
     ylab("R-value") +
     xlab("") +
     geom_hline(yintercept = 1, color = "black", size = 1.2) +
     scale_x_date(date_breaks = "2 days", date_labels = "%d-%b") +
     #scale_y_continuous(breaks = seq(0, 5, 0.25), labels = seq(0, 5, 0.25)) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "grey"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.text = element_text(size = 12, colour = "black"),
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_color_manual(values = c("black")) 
state_r_plot


ggsave("mt_r_local_imported_separate.png")
ggsave("mt_r_local_imported_combined.png")
```

