---
title: "State of Montana Covid-19 Serial Interval Calculation"
author: "Ethan Walker"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 8, fig.height = 6)
```

```{r, message=FALSE}
library(tidyverse)
#library(plyr)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(eeptools)
library(knitr)
library(incidence)
library(EpiEstim)
library(earlyR)
library(projections)
library(distcrete)
library(epitrix)
library(jsonlite)
library(httr)
library(rlist)
library(Rsftp)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", 
               "#0072B2", "#D55E00", "#CC79A7")
colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                        "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")

file_path <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")
```


```{r}
# Load serial interval data
# explanation of data format: https://github.com/jstockwin/EpiEstimApp/wiki/Uploading-your-own-data
mt_si_data_early <- read_xlsx(paste0(file_path, "Input/SI_pair_data.xlsx"), skip = 1,
                        col_names = c("pair_no", "cluster", "infector",
                                      "infector_date", "infected", "infected_date",
                                      "EL", "ER", "SL", "SR"),
                        col_types = c("text", "text", "text",
                                      "date", "text", "date",
                                      "numeric", "numeric", "numeric", "numeric")) %>% 
   filter(infector_date < "2020-05-01" & infected_date < "2020-05-01") %>% 
   select(EL, ER, SL, SR) %>% 
   mutate(SR = if_else(SR == 0, 1, SR)) %>% 
   mutate_all(as.integer)

   mutate(SL2 = if_else(SL<1, SL + (1 - SL), SL),
          SR2 = if_else(SL<1, SR + (1 - SL), SR),
          type = 0) %>% 
   select(EL, ER, SL2, SR2, type) %>% 
   rename(SL = SL2,
          SR = SR2) %>% 
   mutate_all(as.integer)

   
mt_si_data_late <- read_xlsx(paste0(file_path, "Input/SI_pair_data.xlsx"), skip = 1,
                        col_names = c("pair_no", "cluster", "infector",
                                      "infector_date", "infected", "infected_date",
                                      "EL", "ER", "SL", "SR"),
                        col_types = c("text", "text", "text",
                                      "date", "text", "date",
                                      "numeric", "numeric", "numeric", "numeric")) %>% 
   filter(infector_date > "2020-05-01" & infected_date > "2020-05-01") %>% 
   select(EL, ER, SL, SR) %>% 
   mutate(SR = if_else(SR == 0, 1, SR)) %>% 
   mutate_all(as.integer)

   mutate(SL2 = if_else(SL<1, SL + (1 - SL), SL),
          SR2 = if_else(SL<1, SR + (1 - SL), SR),
          type = 0) %>% 
   select(EL, ER, SL2, SR2, type) %>% 
   rename(SL = SL2,
          SR = SR2) %>% 
   mutate_all(as.integer)


# Load/format case data
mt_case_data <- read_xlsx(paste0(file_path, "Input/SI_Local_v_Import Data_10.01.2020.xlsx"),
                                 sheet = 2) %>% 
   rename_all(tolower) %>% 
   select(-case_no) %>% 
   rownames_to_column(var = "case_no") %>% 
   mutate(local = if_else(local_import == 0, 1, 0),
          imported = local_import,
          date_reported = ymd(date_reported),
          dates = as.Date(symptom_onset_date),
          dates = ymd(dates),
          case = 1) %>% 
   rename(hospitalization = "ever_hospitalized") %>% 
   mutate(age_group_new = if_else(age_group == "80-89" | age_group == "90-99",
                               "80+", age_group),
          age_group_new = factor(age_group_new, 
                                 levels = c("0-9", "10-19", "20-29", 
                                            "30-39", "40-49", "50-59", 
                                            "60-69", "70-79", "80+"),
                                 labels = c("0 to 9", "10 to 19", "20 to 29", 
                                            "30 to 39", "40 to 49", "50 to 59", 
                                            "60 to 69", "70 to 79", "80+"))) %>% 
   mutate(hospitalization = factor(hospitalization,
                                   levels = c("Y", "N", "P", "U"),
                                   labels = c("Hosp: Yes", "Hosp: No", 
                                              "Hosp: Past", "Hosp: Unknown"))) %>% 
   filter(!is.na(dates)) %>% 
   arrange(dates) %>% 
   ungroup() %>% 
   select(case_no, mt_case, county:hospitalization, local_import:age_group_new)
```


```{r}
#################### Run analysis and print results
## State results
# Format analysis data
mt_li_analysis_data <- mt_case_data %>% 
   filter(dates < "2020-05-01") %>% 
   group_by(dates) %>% 
   mutate(local = sum(local),
          imported = sum(imported)) %>% 
   select(dates, local, imported) %>% 
   distinct(dates, .keep_all = TRUE) %>% 
   arrange(dates)


mt_data <- mt_li_analysis_data %>% 
   mutate(I = local + imported) %>% 
   select(dates, I) 

latest_date <- format(Sys.Date() - 14, "%Y-%m-%d")

mt_incidence_data <- incidence(mt_data$dates, last_date = "2020-04-30")

mt_li_inc_data <- as.data.frame(mt_incidence_data$dates) %>% 
   mutate(dates = ymd(mt_incidence_data$dates)) %>% 
   select(dates) %>% 
   left_join(mt_li_analysis_data, by = "dates") %>% 
   mutate(local = if_else(is.na(local), 0, local),
          imported = if_else(is.na(imported), 0, imported))


state_n <- as.data.frame(mt_li_inc_data$dates)
time_var <- nrow(state_n)
time_start <- seq(2, time_var-13)
time_end <- time_start + 13

## This code uses paired cases to calculate a serial interval
## I tried this code with various burnin and n1 settings, giving essentially the same results
## Once the SI is calculated from this code, the mean SI and SD SI can then be used in other files to the run analysis
## This code only needs to be used if we want to update the SI with new paired cases
MCMC_seed <- 1
overall_seed <- 2
mcmc_control <- make_mcmc_control(seed = MCMC_seed, burnin = 10000, thin = 10)
dist <- "G"  # fitting a Gamma distribution for the SI
si_config <- make_config(list(si_parametric_distr = dist, 
                              mcmc_control = mcmc_control, seed = overall_seed, n1 = 5000, n2 = 500,
                              t_start = time_start, t_end = time_end))

mt_r_results <- estimate_R(mt_li_inc_data, method = "si_from_data", 
                           si_data = mt_si_data, config = si_config)

serial_interval_mean <- 6.53
serial_interval_sd <- 5.44

mt_r_results <- estimate_R(mt_li_inc_data, method = "parametric_si", 
                              config = make_config(list(mean_si = serial_interval_mean, 
                                                        std_si = serial_interval_sd,
                                                        t_start =  2,
                                                        t_end = 61)))


# calculate mean serial interval using SI data
# Mean SI = 6.3, SD SI = 5.4
mean_si <- mt_r_results$SI.Moments %>% 
   summarize(mean_si = mean(Mean), sd_si = mean(Std)) 
mean_si

colomns <- c(1:4, 8)
state_r <- (mt_r_results$R[,colomns]) %>% 
   mutate(region = "state") %>% 
   rename(mean_r = `Mean(R)`,
          sd_r = `Std(R)`,
          median_r = `Median(R)`)

state_dates <- as.data.frame(mt_r_results$dates)
state_i <- as.data.frame(mt_r_results$I)
state_cil <- as.data.frame(mt_r_results$R$`Quantile.0.025(R)`)
state_cih <- as.data.frame(mt_r_results$R$`Quantile.0.975(R)`)
state_dates_new <- cbind(state_dates, state_i) %>% 
   rename(dates = 1,
          incidence = 2) %>% 
   mutate(dates = ymd(dates))
state_dates_new <- state_dates_new[-(1:14), 1:2]
state_dates_new <- cbind(state_dates_new, state_cil, state_cih) %>% 
   rename(cl_low = 3,
          cl_high = 4)
state_r_clean <- cbind(state_r, state_dates_new)

total_cases <- sum(mt_case_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")


state_r_plot <- state_r_clean %>% 
   ggplot() +
   geom_line(aes(dates, mean_r), size = 1.5, color = "black") +
   geom_line(aes(dates, cl_low), size = 1.5, color = "grey") +
   geom_line(aes(dates, cl_high), size = 1.5, color = "grey") +
   labs(title = "COVID-19 Rolling 14-day R-values, State of Montana, 2020",
        color = "") +
   ylab("R-value") +
   xlab("") +
   geom_hline(yintercept = 1, color = "black", size = 1.2) +
   scale_x_date(date_breaks = "3 days", date_labels = "%d-%b") +
   scale_y_continuous(breaks = seq(0, 10, 0.5), labels = seq(0, 10, 0.5)) +
   theme_minimal() +
   theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 12, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 12, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 12, colour = "black"),
         legend.text = element_text(size = 12, colour = "black"),
         axis.title.y = element_text(size = 12, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 12, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) +
   scale_color_manual(values = c("black")) 
state_r_plot
#ggsave("C:/R/covid19/state_daily_results/state_r_plot.png", width = 10, height = 8)

state_inc_plot <- mt_case_data %>% 
   ggplot() +
   geom_col(aes(dates, case), 
            fill = "steelblue") +
   labs(title = paste0("COVID-19 Cases in State of Montana, 2020", 
                       " (Total cases = ", total_cases, ")"),
        subtitle = paste0("Data current as of ", date_today)) +
   ylab("Number of Cases") +
   xlab("") +
   scale_x_date(date_breaks = "3 day", date_labels = "%d-%b") +
   theme_minimal() +
   theme(strip.text = element_text(size = 16, colour = "black"),
         title = element_text(size = 12, colour = "black"),
         panel.grid = element_blank(),
         panel.grid.major.y = element_line(colour = "grey"),
         axis.text.x = element_text(size = 12, colour = "black", 
                                    angle = 90, vjust = 0.4),
         axis.text.y = element_text(size = 12, colour = "black"),
         axis.title.y = element_text(size = 12, colour = "black",
                                     margin = unit(c(0, 5, 0, 0), "mm")),
         axis.title.x = element_text(size = 12, colour = "black",
                                     margin = unit(c(5, 0, 0, 0), "mm")),
         axis.line.x = element_blank(), 
         axis.line.y = element_blank(), 
         axis.ticks = element_blank()) 
state_inc_plot
#ggsave("C:/R/covid19/state_daily_results/state_inc_plot.png", width = 10, height = 8)
```


# SI Publication Plots
```{r, fig.width = 10, fig.height = 5}
colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                        "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")

plot_colors <- c("#332288", "#882255", "#661100", "#6699CC", "#888888")

# Epi curve - test date
full_data <- mt_case_data %>% 
   filter(dates < "2020-08-01")

total_cases <- sum(mt_case_data$case)
date_today <- format(Sys.Date(), "%d %b %Y")
date_14 <- format(Sys.Date() - 14, "%d %b %Y")

epi_curve_full <- full_data %>% 
   mutate(local_import = factor(local_import,
                            levels = c(1, 0),
                            labels = c("imported case", "local case"))) %>% 
   ggplot() +
     geom_rect(aes(xmin = as.Date("2020-05-01"), xmax = as.Date("2020-08-01"), ymin=0, ymax=Inf),
               fill = "gray70", alpha = 0.05) +
     geom_rect(aes(xmin = as.Date("2020-02-28"), xmax = as.Date("2020-05-01"), ymin=0, ymax=Inf),
               fill = "gray50", alpha = 0.05) +
     geom_col(aes(dates, case, fill = local_import), width = 1) +
     geom_label(aes(x = as.Date("2020-03-31"), y = 125,
                    label = "Early cases: \n n = 462 \n Pairs = 116 \n Mean SI = 6.53 \n SD SI = 5.44 \n Mean R = 0.67"),
                fill = NA, color = "black") +
     geom_label(aes(x = as.Date("2020-06-15"), y = 125, 
                    label = "Later cases: \n n = xx \n Pairs = xx \n Mean SI = xx \n SD SI = xx \n Mean R = xx"),
                fill = NA, color = "black") +
     labs(title = "COVID-19 cases in Montana by date of symptom onset",
          subtitle = paste0("Total cases: n = xx, Pairs = xx, Mean SI = xx, SD SI = xx, Mean R = xx"),
          fill = " ") +
     ylab("Number of Cases") +
     xlab("") +
     scale_x_date(breaks = seq.Date(from = as.Date("2020-03-01"), 
                                    to = as.Date("2020-08-01"), 
                                    by = "5 days"),
                  labels = seq.Date(from = as.Date("2020-03-01"), 
                                    to = as.Date("2020-08-01"), 
                                    by = "5 days"),
                  date_labels = "%d-%b") +
     scale_y_continuous(breaks = c(seq(0, 300, 25)), labels = c(seq(0, 300, 25))) +
     theme_minimal() +
     theme(strip.text = element_text(size = 16, colour = "black"),
           title = element_text(size = 12, colour = "black"),
           panel.grid = element_blank(),
           panel.grid.major.y = element_line(colour = "gray75"),
           axis.text.x = element_text(size = 12, colour = "black", 
                                     angle = 90, vjust = 0.4),
           axis.text.y = element_text(size = 12, colour = "black"),
           legend.position = "top",
           axis.title.y = element_text(size = 12, colour = "black",
                                       margin = unit(c(0, 5, 0, 0), "mm")),
           axis.title.x = element_text(size = 12, colour = "black",
                                       margin = unit(c(5, 0, 0, 0), "mm")),
           legend.text = element_text(size = 12, colour = "black"),
           axis.line.x = element_blank(), 
           axis.line.y = element_blank(), 
           axis.ticks = element_blank()) +
     scale_fill_manual(values = plot_colors)   

epi_curve_full

#ggsave("si_pub_epi_curve.jpg", width = 10, height = 5)
```


