---
title: "Montana COVID-19 Sociodemographic/Spatial Analysis"
author: "Ethan Walker, University of Montana"
date: "Started Oct 2, 2020, Updated Oct 7, 2020"
output: pdf_document
header-includes:
    - \usepackage[labelformat=empty, font={Large, bf}]{caption}
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, 
                      include = TRUE, warning = FALSE, message = FALSE,
                      fig.width = 10, fig.height = 6)
```

```{r, message=FALSE}
library(tidyverse)
library(readxl)
library(naniar)
library(lubridate)
library(zoo)
library(eeptools)
library(knitr)
library(incidence)
library(EpiEstim)
library(earlyR)
library(projections)
library(distcrete)
library(epitrix)
library(jsonlite)
library(httr)
library(rlist)
library(Rsftp)
library(googledrive)
library(googlesheets4)
library(data.table)
library(ggmap)
library(maps)
library(tigris)
library(usmap)
library(GISTools)
library(geosphere)
jv_palette <- c("#330099","#CC0066","#FF6633", 
                 "#0099CC", "#FF9900","#CC6633",
                  "#FF3366", "#33CC99", "#33999")
cbPalette <- c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#CC6633",
               "#0072B2", "#D55E00", "#CC79A7", "#999999")
colorblind_palette <- c("#88CCEE", "#CC6677", "#DDCC77", "#117733", "#332288", "#AA4499", 
                        "#44AA99", "#999933", "#882255", "#661100", "#6699CC", "#888888")
```


```{r}
############## Query and prep state case data
query_url <- "https://services.arcgis.com/qnjIrwR8z5Izc0ij/ArcGIS/rest/services/COVID_Cases_Production_View/FeatureServer/2/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=OBJECTID%2C+Case_No%2C+Date_Reported_to_CDEpi%2C+County%2C+Age_Group%2C+Sex%2C+Hospitalization%2C+Outcome%2C+MT_case&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pjson&token="

initial_pull <- GET(query_url)

text_data <- content(initial_pull, as = "text")

parsed_data <- content(initial_pull, as = "parsed")

json_data <- fromJSON(text_data)

state_data <- as.data.frame(json_data$features$attributes) 

reg1 <- as.data.frame(c("Carter", "Custer", "Daniels", "Dawson", "Fallon", "Garfield", "McCone",
                        "Phillips", "Powder River", "Prairie", "Richland", "Roosevelt", "Rosebud",
                        "Sheridan", "Treasure", "Valley", "Wibaux")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 1)

reg2 <- as.data.frame(c("Blaine", "Cascade", "Chouteau", "Glacier", "Hill", "Liberty", "Pondera",
                        "Teton", "Toole")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 2)

reg3 <- as.data.frame(c("Big Horn", "Carbon", "Fergus", "Golden Valley", "Judith Basin",
                        "Musselshell", "Petroleum", "Stillwater", "Sweet Grass", "Wheatland",
                        "Yellowstone")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 3)

reg4 <- as.data.frame(c("Beaverhead", "Broadwater", "Deer Lodge", "Gallatin", "Granite", "Jefferson",
                        "Lewis and Clark", "Madison", "Meagher", "Park", "Powell", "Silver Bow")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 4)

reg5 <- as.data.frame(c("Flathead", "Lake", "Lincoln", "Mineral", "Missoula", 
                        "Ravalli", "Sanders")) %>% 
   rename_at(1, ~"county") %>% 
   mutate(region = 5)

counties_regions <- rbind(reg1, reg2, reg3, reg4, reg5)

state_data_clean <- state_data %>% 
   rename_all(tolower) %>% 
   mutate(date_reported_to_cdepi = date_reported_to_cdepi/1000,
          dates = as.POSIXct(date_reported_to_cdepi, origin = "1970-01-01")) %>% 
   separate(dates, c("dates", "trash"), sep = " ") %>% 
   mutate(dates = ymd(dates)) %>% 
   select(case_no, dates, county:mt_case) %>% 
   left_join(counties_regions, by = "county") %>% 
   mutate(case = 1) %>% 
   mutate(age_group2 = if_else(age_group == "80-89" | age_group == "90-99",
                               "80+", age_group),
          age_group_new = factor(age_group2, 
                                 levels = c("0-9", "10-19", "20-29", 
                                            "30-39", "40-49", "50-59", 
                                            "60-69", "70-79", "80+"),
                                 labels = c("0 to 9, 0.12", "10 to 19, 0.12", "20 to 29, 0.13", 
                                            "30 to 39, 0.13", "40 to 49, 0.11", "50 to 59, 0.12", 
                                            "60 to 69, 0.14", "70 to 79, 0.08", "80+, 0.04"))) %>% 
   separate(age_group_new, c("age_group_new", "age_group_new_percent"), sep = ",") %>% 
   mutate(age_group_new_percent = as.numeric(age_group_new_percent),
          state_pop = as.numeric(1068778)) %>% 
   select(-age_group2, -age_group_new, -age_group_new_percent, -state_pop) %>% 
   mutate(hospitalization = factor(hospitalization,
                                   levels = c("Y", "N", "P", "U"),
                                   labels = c("Hosp: Yes", "Hosp: No", 
                                              "Hosp: Past", "Hosp: Unknown"))) %>% 
   select(-case_no) %>% 
   rownames_to_column(var = "case_no")


# Pull in and merge other data files
file_path1 <- c("C:/Users/ethan.walker/Box/COVID19 Spatial/")
file_path2 <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")

county_data_initial <- read_csv(paste0(file_path1, "MASTERfiles/Montana_COUNTY_Master.csv")) %>% 
   rename_all(tolower) %>% 
   mutate(state_pop = sum(e_totpop))

covid_county_merged <- state_data_clean %>% 
   left_join(county_data_initial, by = "county") %>% 
   ungroup() %>% 
   arrange(county, dates)

write_csv(covid_county_merged, paste0(file_path1, "merged_data/covid_county_merged.csv"))
write_rds(covid_county_merged, paste0(file_path2, "Output/covid_county_merged.rds"))
```


```{r}
# Initial analysis and summary results
file_path2 <- c("C:/Users/ethan.walker/Box/Ethan Walker UM/R/covid19/")
covid_county_merged <- read_rds(paste0(file_path2, "Output/covid_county_merged.rds"))

cleaning_data <- covid_county_merged %>% 
   mutate(month_of_year = lubridate::month(dates, label = TRUE)) %>% 
   ungroup() %>% 
   mutate(state_cases = sum(case)) %>% 
   group_by(month_of_year) %>% 
   mutate(state_month_cases = sum(case)) %>% 
   group_by(age_group) %>% 
   mutate(state_age_group_cases = sum(case)) %>% 
   group_by(sex) %>% 
   mutate(state_sex_cases = sum(case)) %>% 
   group_by(hospitalization) %>% 
   mutate(state_hospitalization_cases = sum(case)) %>% 
   group_by(outcome) %>% 
   mutate(state_outcome_cases = sum(case)) %>% 
   group_by(county) %>% 
   mutate(county_cases = sum(case)) %>% 
   group_by(county, month_of_year) %>% 
   mutate(county_month_cases = sum(case)) %>% 
   group_by(county, age_group) %>% 
   mutate(county_age_group_cases = sum(case)) %>% 
   group_by(county, sex) %>% 
   mutate(county_sex_cases = sum(case)) %>% 
   group_by(county, hospitalization) %>% 
   mutate(county_hospitalization_cases = sum(case)) %>% 
   group_by(county, outcome) %>% 
   mutate(county_outcome_cases = sum(case)) %>% 
   group_by(region) %>% 
   mutate(region_cases = sum(case)) %>% 
   group_by(region, month_of_year) %>% 
   mutate(region_month_cases = sum(case)) %>% 
   group_by(region, age_group) %>% 
   mutate(region_age_group_cases = sum(case)) %>% 
   group_by(region, sex) %>% 
   mutate(region_sex_cases = sum(case)) %>% 
   group_by(region, hospitalization) %>% 
   mutate(region_hospitalization_cases = sum(case)) %>% 
   group_by(region, outcome) %>% 
   mutate(region_outcome_cases = sum(case)) %>% 
   ungroup()

county_data <- cleaning_data %>% 
   distinct(county, month_of_year, age_group, sex, hospitalization, outcome, .keep_all = TRUE) %>% 
   dplyr::select(-mt_case, -case, -case_no, -dates) %>% 
   arrange(county, month_of_year, age_group, sex, hospitalization, outcome) %>% 
   mutate(state_inc = state_cases/state_pop*100000) %>% 
   group_by(county) %>% 
   mutate(county_inc = county_cases/e_totpop*100000) %>% 
   ungroup() %>% 
   mutate(county_state_inc_ratio = round(county_inc/state_inc, digits = 2)) %>% 
   dplyr::select(state_cases, state_inc, county, region, county_cases, county_inc, county_state_inc_ratio,
          month_of_year, state_month_cases, county_month_cases, region_month_cases,
          age_group, state_age_group_cases, county_age_group_cases, region_age_group_cases,
          sex, state_sex_cases, county_sex_cases, region_sex_cases,
          hospitalization, state_hospitalization_cases, county_hospitalization_cases, region_hospitalization_cases,
          outcome, state_outcome_cases, county_outcome_cases, region_outcome_cases,
          st:region_outcome_cases) 

inc_ratio_summary <- county_data %>% 
   dplyr::select(county, county_inc, county_state_inc_ratio) %>% 
   distinct(county, .keep_all = TRUE) %>% 
   mutate(county = tolower(county)) %>% 
   arrange(county_state_inc_ratio)
head(inc_ratio_summary, 10)

inc_ratio_summary <- county_data %>% 
   dplyr::select(county, county_inc, county_state_inc_ratio) %>% 
   distinct(county, .keep_all = TRUE) %>% 
   arrange(desc(county_state_inc_ratio))
head(inc_ratio_summary, 10)
```


```{r}
# Montana map
mt_map <- map_data("county") %>% 
   filter(region == "montana") %>% 
   rename(county = subregion) %>% 
   filter(county != "yellowstone national") %>% 
   left_join(inc_ratio_summary, by = "county") %>% 
   mutate(inc_cat = gtools::quantcut(county_inc, 4),
          inc_cat = gsub("\\(", "", inc_cat),
          inc_cat = gsub("]", "", inc_cat),
          inc_cat = gsub("\\[", "", inc_cat)) %>% 
   separate(inc_cat, c("range1", "range2"), sep = ",") %>% 
   mutate(range1 = as.numeric(range1),
          range2 = as.numeric(range2)) %>% 
   unite(inc_cat, c("range1", "range2"), sep = " to ", remove = FALSE) %>% 
   arrange(range1) %>% 
   mutate(inc_cat = factor(inc_cat,
                           levels = c("166 to 754", "754 to 1180",
                                      "1180 to 1660", "1660 to 7590")))


mt_map <- us_map(regions = "counties") %>% 
   filter(full == "Montana") %>% 
   mutate(fips = as.numeric(fips)) %>% 
   select(-county) %>% 
   left_join(inc_ratio_summary, by = "fips") %>% 
   group_by(county) %>% 
   mutate(mean_x = mean(x),
          mean_y = mean(y)) %>% 
   ungroup() %>% 
   mutate(inc_ratio_cat = cut(county_state_inc_ratio,
                              breaks = c(0, 0.48, 0.75, 1.06, 4.86),
                              labels = c("0 to 0.47", "0.48 to 0.74",
                                         "0.75 to 1.05", "1.06 to 4.85"),
                              right = FALSE)) 
mt_map


mt_plot <- mt_map %>% 
  ggplot() +
    geom_polygon(aes(long, lat, group=group, fill = inc_cat), 
                 colour="black", size = 1.2, angle = 90) +
    #geom_point(aes(x=mean_x, y=mean_y, size = county_state_inc_ratio)) +
    theme_void() +
    labs(title = "  Montana COVID-19 incidence, by quartile", fill = "Incidence") +
    scale_fill_brewer(palette = "Blues")
mt_plot

```

